//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Web.bus_user {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtuser_type;
		protected global::System.Web.UI.WebControls.TextBox txtpwd;
		protected global::System.Web.UI.WebControls.TextBox txtnickname;
		protected global::System.Web.UI.WebControls.TextBox txtstatus;
		protected global::System.Web.UI.WebControls.TextBox txtphone_num;
		protected global::System.Web.UI.WebControls.TextBox txtpic_url;
		protected global::System.Web.UI.WebControls.TextBox txtsex;
		protected global::System.Web.UI.WebControls.TextBox txtgenerate_time;
		protected global::System.Web.UI.WebControls.TextBox txtcur_deviceId;
		protected global::System.Web.UI.WebControls.TextBox txtis_delete;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
		protected global::System.Web.UI.WebControls.TextBox txtcreate_by;
		protected global::System.Web.UI.WebControls.TextBox txtcreate_date;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_by;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_date;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
