//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Web.bus_pickup_address {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblpickup_code;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lbladdress;
	protected global::System.Web.UI.WebControls.Label lblarea_id;
	protected global::System.Web.UI.WebControls.Label lbllon;
	protected global::System.Web.UI.WebControls.Label lbllat;
	protected global::System.Web.UI.WebControls.Label lblstatus;
	protected global::System.Web.UI.WebControls.Label lbldilivery_user_id;
	protected global::System.Web.UI.WebControls.Label lblsort;
	protected global::System.Web.UI.WebControls.Label lblis_delete;
	protected global::System.Web.UI.WebControls.Label lblremark;
	protected global::System.Web.UI.WebControls.Label lblcreate_by;
	protected global::System.Web.UI.WebControls.Label lblcreate_date;
	protected global::System.Web.UI.WebControls.Label lblupdate_by;
	protected global::System.Web.UI.WebControls.Label lblupdate_date;


       
    }
}
