// You can find instructions for this file here:
// http://www.treeview.net

// Decide if the names are links or just the icons
USETEXTLINKS = 1  //replace 0 with 1 for hyperlinks

// Decide if the tree is to start all open or just showing the root folders
STARTALLOPEN = 0 //replace 0 with 1 to show the whole tree

ICONPATH = 'Support/' //change if the gif's folder is a subfolder, for example: 'images/'


USEICONS = 1

{
foldersTree = gFld("Title", "title.htm")
foldersTree.iconSrc = ICONPATH + "Gif/globe.gif"
Diag_Node = insFld(foldersTree, gFld("DB.DM1", "javascript:parent.op()"))
Diag_Node.iconSrc = ICONPATH + "Gif/ERSTUDIO.gif"
Diag_Node.iconSrcClosed = ICONPATH + "Gif/ERSTUDIO.gif"
Model_Node = insFld(Diag_Node, gFld("bui_dbv1.0", "javascript:parent.op()"))
Model_Node.iconSrc = ICONPATH + "Gif/physical.gif"
Model_Node.iconSrcClosed = ICONPATH + "Gif/physical.gif"
{
Submodel8 = insFld(Model_Node, gFld("Main Model", "javascript:parent.op()"))
Submodel8.iconSrc = ICONPATH + "Gif/grnfldr.gif"
Submodel8.iconSrcClosed = ICONPATH + "Gif/grnfldr.gif"
SubmodelImgNode = insDoc(Submodel8, gLnk("R", "Model Image", "Model8/Submodel8_img.htm"))
SubmodelImgNode.iconSrc = ICONPATH + "Gif/image.gif"
SubmodelImgNode.altTxt = "Model Image"
{
EntityFolder = insFld(Submodel8, gFld("Tables", "javascript:parent.op()"))
EntityFolder.iconSrc = ICONPATH + "Gif/entfldr.gif"
EntityFolder.iconSrcClosed = ICONPATH + "Gif/entfldr.gif"
Tbl38 = insFld(EntityFolder, gFld("bus_area", "Model8/Tbl38.htm"))
Tbl38.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl38.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr440 = insDoc(Tbl38, gLnk("R", "id", "Model8/Tbl38_Attr.htm#Attr440"))
Attr440.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr440.altTxt = "Primary Key"
Attr441 = insDoc(Tbl38, gLnk("R", "parent_id", "Model8/Tbl38_Attr.htm#Attr441"))
Attr441.iconSrc = ICONPATH + "Gif/attr.gif"
Attr441.altTxt = "Column"
Attr442 = insDoc(Tbl38, gLnk("R", "name", "Model8/Tbl38_Attr.htm#Attr442"))
Attr442.iconSrc = ICONPATH + "Gif/attr.gif"
Attr442.altTxt = "Column"
Attr447 = insDoc(Tbl38, gLnk("R", "area_type", "Model8/Tbl38_Attr.htm#Attr447"))
Attr447.iconSrc = ICONPATH + "Gif/attr.gif"
Attr447.altTxt = "Column"
Attr443 = insDoc(Tbl38, gLnk("R", "lon", "Model8/Tbl38_Attr.htm#Attr443"))
Attr443.iconSrc = ICONPATH + "Gif/attr.gif"
Attr443.altTxt = "Column"
Attr444 = insDoc(Tbl38, gLnk("R", "lat", "Model8/Tbl38_Attr.htm#Attr444"))
Attr444.iconSrc = ICONPATH + "Gif/attr.gif"
Attr444.altTxt = "Column"
Attr451 = insDoc(Tbl38, gLnk("R", "is_delete", "Model8/Tbl38_Attr.htm#Attr451"))
Attr451.iconSrc = ICONPATH + "Gif/attr.gif"
Attr451.altTxt = "Column"
Attr445 = insDoc(Tbl38, gLnk("R", "remark", "Model8/Tbl38_Attr.htm#Attr445"))
Attr445.iconSrc = ICONPATH + "Gif/attr.gif"
Attr445.altTxt = "Column"
Attr446 = insDoc(Tbl38, gLnk("R", "create_by", "Model8/Tbl38_Attr.htm#Attr446"))
Attr446.iconSrc = ICONPATH + "Gif/attr.gif"
Attr446.altTxt = "Column"
Attr448 = insDoc(Tbl38, gLnk("R", "create_date", "Model8/Tbl38_Attr.htm#Attr448"))
Attr448.iconSrc = ICONPATH + "Gif/attr.gif"
Attr448.altTxt = "Column"
Attr449 = insDoc(Tbl38, gLnk("R", "update_by", "Model8/Tbl38_Attr.htm#Attr449"))
Attr449.iconSrc = ICONPATH + "Gif/attr.gif"
Attr449.altTxt = "Column"
Attr450 = insDoc(Tbl38, gLnk("R", "update_date", "Model8/Tbl38_Attr.htm#Attr450"))
Attr450.iconSrc = ICONPATH + "Gif/attr.gif"
Attr450.altTxt = "Column"
}
Tbl40 = insFld(EntityFolder, gFld("bus_dish", "Model8/Tbl40.htm"))
Tbl40.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl40.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr471 = insDoc(Tbl40, gLnk("R", "id", "Model8/Tbl40_Attr.htm#Attr471"))
Attr471.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr471.altTxt = "Primary Key"
Attr472 = insDoc(Tbl40, gLnk("R", "market_id", "Model8/Tbl40_Attr.htm#Attr472"))
Attr472.iconSrc = ICONPATH + "Gif/attr.gif"
Attr472.altTxt = "Column"
Attr473 = insDoc(Tbl40, gLnk("R", "dish_type", "Model8/Tbl40_Attr.htm#Attr473"))
Attr473.iconSrc = ICONPATH + "Gif/attr.gif"
Attr473.altTxt = "Column"
Attr474 = insDoc(Tbl40, gLnk("R", "name_en", "Model8/Tbl40_Attr.htm#Attr474"))
Attr474.iconSrc = ICONPATH + "Gif/attr.gif"
Attr474.altTxt = "Column"
Attr483 = insDoc(Tbl40, gLnk("R", "name_cn", "Model8/Tbl40_Attr.htm#Attr483"))
Attr483.iconSrc = ICONPATH + "Gif/attr.gif"
Attr483.altTxt = "Column"
Attr475 = insDoc(Tbl40, gLnk("R", "description_en", "Model8/Tbl40_Attr.htm#Attr475"))
Attr475.iconSrc = ICONPATH + "Gif/attr.gif"
Attr475.altTxt = "Column"
Attr484 = insDoc(Tbl40, gLnk("R", "description_cn", "Model8/Tbl40_Attr.htm#Attr484"))
Attr484.iconSrc = ICONPATH + "Gif/attr.gif"
Attr484.altTxt = "Column"
Attr486 = insDoc(Tbl40, gLnk("R", "original_price", "Model8/Tbl40_Attr.htm#Attr486"))
Attr486.iconSrc = ICONPATH + "Gif/attr.gif"
Attr486.altTxt = "Column"
Attr487 = insDoc(Tbl40, gLnk("R", "discount_price", "Model8/Tbl40_Attr.htm#Attr487"))
Attr487.iconSrc = ICONPATH + "Gif/attr.gif"
Attr487.altTxt = "Column"
Attr476 = insDoc(Tbl40, gLnk("R", "sales_total", "Model8/Tbl40_Attr.htm#Attr476"))
Attr476.iconSrc = ICONPATH + "Gif/attr.gif"
Attr476.altTxt = "Column"
Attr485 = insDoc(Tbl40, gLnk("R", "sort", "Model8/Tbl40_Attr.htm#Attr485"))
Attr485.iconSrc = ICONPATH + "Gif/attr.gif"
Attr485.altTxt = "Column"
Attr482 = insDoc(Tbl40, gLnk("R", "is_delete", "Model8/Tbl40_Attr.htm#Attr482"))
Attr482.iconSrc = ICONPATH + "Gif/attr.gif"
Attr482.altTxt = "Column"
Attr477 = insDoc(Tbl40, gLnk("R", "remark", "Model8/Tbl40_Attr.htm#Attr477"))
Attr477.iconSrc = ICONPATH + "Gif/attr.gif"
Attr477.altTxt = "Column"
Attr478 = insDoc(Tbl40, gLnk("R", "create_by", "Model8/Tbl40_Attr.htm#Attr478"))
Attr478.iconSrc = ICONPATH + "Gif/attr.gif"
Attr478.altTxt = "Column"
Attr479 = insDoc(Tbl40, gLnk("R", "create_date", "Model8/Tbl40_Attr.htm#Attr479"))
Attr479.iconSrc = ICONPATH + "Gif/attr.gif"
Attr479.altTxt = "Column"
Attr480 = insDoc(Tbl40, gLnk("R", "update_by", "Model8/Tbl40_Attr.htm#Attr480"))
Attr480.iconSrc = ICONPATH + "Gif/attr.gif"
Attr480.altTxt = "Column"
Attr481 = insDoc(Tbl40, gLnk("R", "update_date", "Model8/Tbl40_Attr.htm#Attr481"))
Attr481.iconSrc = ICONPATH + "Gif/attr.gif"
Attr481.altTxt = "Column"
}
Tbl41 = insFld(EntityFolder, gFld("bus_dish_plan", "Model8/Tbl41.htm"))
Tbl41.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl41.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr488 = insDoc(Tbl41, gLnk("R", "id", "Model8/Tbl41_Attr.htm#Attr488"))
Attr488.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr488.altTxt = "Primary Key"
Attr489 = insDoc(Tbl41, gLnk("R", "dish_id", "Model8/Tbl41_Attr.htm#Attr489"))
Attr489.iconSrc = ICONPATH + "Gif/attr.gif"
Attr489.altTxt = "Column"
Attr490 = insDoc(Tbl41, gLnk("R", "start_date", "Model8/Tbl41_Attr.htm#Attr490"))
Attr490.iconSrc = ICONPATH + "Gif/attr.gif"
Attr490.altTxt = "Column"
Attr491 = insDoc(Tbl41, gLnk("R", "end_date", "Model8/Tbl41_Attr.htm#Attr491"))
Attr491.iconSrc = ICONPATH + "Gif/attr.gif"
Attr491.altTxt = "Column"
Attr492 = insDoc(Tbl41, gLnk("R", "dish_type", "Model8/Tbl41_Attr.htm#Attr492"))
Attr492.iconSrc = ICONPATH + "Gif/attr.gif"
Attr492.altTxt = "Column"
Attr493 = insDoc(Tbl41, gLnk("R", "is_delete", "Model8/Tbl41_Attr.htm#Attr493"))
Attr493.iconSrc = ICONPATH + "Gif/attr.gif"
Attr493.altTxt = "Column"
Attr494 = insDoc(Tbl41, gLnk("R", "remark", "Model8/Tbl41_Attr.htm#Attr494"))
Attr494.iconSrc = ICONPATH + "Gif/attr.gif"
Attr494.altTxt = "Column"
Attr495 = insDoc(Tbl41, gLnk("R", "create_by", "Model8/Tbl41_Attr.htm#Attr495"))
Attr495.iconSrc = ICONPATH + "Gif/attr.gif"
Attr495.altTxt = "Column"
Attr496 = insDoc(Tbl41, gLnk("R", "create_date", "Model8/Tbl41_Attr.htm#Attr496"))
Attr496.iconSrc = ICONPATH + "Gif/attr.gif"
Attr496.altTxt = "Column"
Attr497 = insDoc(Tbl41, gLnk("R", "update_by", "Model8/Tbl41_Attr.htm#Attr497"))
Attr497.iconSrc = ICONPATH + "Gif/attr.gif"
Attr497.altTxt = "Column"
Attr498 = insDoc(Tbl41, gLnk("R", "update_date", "Model8/Tbl41_Attr.htm#Attr498"))
Attr498.iconSrc = ICONPATH + "Gif/attr.gif"
Attr498.altTxt = "Column"
}
Tbl48 = insFld(EntityFolder, gFld("bus_image", "Model8/Tbl48.htm"))
Tbl48.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl48.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr564 = insDoc(Tbl48, gLnk("R", "id", "Model8/Tbl48_Attr.htm#Attr564"))
Attr564.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr564.altTxt = "Primary Key"
Attr565 = insDoc(Tbl48, gLnk("R", "bus_type", "Model8/Tbl48_Attr.htm#Attr565"))
Attr565.iconSrc = ICONPATH + "Gif/attr.gif"
Attr565.altTxt = "Column"
Attr566 = insDoc(Tbl48, gLnk("R", "img_type", "Model8/Tbl48_Attr.htm#Attr566"))
Attr566.iconSrc = ICONPATH + "Gif/attr.gif"
Attr566.altTxt = "Column"
Attr567 = insDoc(Tbl48, gLnk("R", "url", "Model8/Tbl48_Attr.htm#Attr567"))
Attr567.iconSrc = ICONPATH + "Gif/attr.gif"
Attr567.altTxt = "Column"
Attr574 = insDoc(Tbl48, gLnk("R", "sort", "Model8/Tbl48_Attr.htm#Attr574"))
Attr574.iconSrc = ICONPATH + "Gif/attr.gif"
Attr574.altTxt = "Column"
Attr568 = insDoc(Tbl48, gLnk("R", "is_delete", "Model8/Tbl48_Attr.htm#Attr568"))
Attr568.iconSrc = ICONPATH + "Gif/attr.gif"
Attr568.altTxt = "Column"
Attr569 = insDoc(Tbl48, gLnk("R", "remark", "Model8/Tbl48_Attr.htm#Attr569"))
Attr569.iconSrc = ICONPATH + "Gif/attr.gif"
Attr569.altTxt = "Column"
Attr570 = insDoc(Tbl48, gLnk("R", "create_by", "Model8/Tbl48_Attr.htm#Attr570"))
Attr570.iconSrc = ICONPATH + "Gif/attr.gif"
Attr570.altTxt = "Column"
Attr571 = insDoc(Tbl48, gLnk("R", "create_date", "Model8/Tbl48_Attr.htm#Attr571"))
Attr571.iconSrc = ICONPATH + "Gif/attr.gif"
Attr571.altTxt = "Column"
Attr572 = insDoc(Tbl48, gLnk("R", "update_by", "Model8/Tbl48_Attr.htm#Attr572"))
Attr572.iconSrc = ICONPATH + "Gif/attr.gif"
Attr572.altTxt = "Column"
Attr573 = insDoc(Tbl48, gLnk("R", "update_date", "Model8/Tbl48_Attr.htm#Attr573"))
Attr573.iconSrc = ICONPATH + "Gif/attr.gif"
Attr573.altTxt = "Column"
}
Tbl39 = insFld(EntityFolder, gFld("bus_market", "Model8/Tbl39.htm"))
Tbl39.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl39.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr452 = insDoc(Tbl39, gLnk("R", "id", "Model8/Tbl39_Attr.htm#Attr452"))
Attr452.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr452.altTxt = "Primary Key"
Attr470 = insDoc(Tbl39, gLnk("R", "markket_code", "Model8/Tbl39_Attr.htm#Attr470"))
Attr470.iconSrc = ICONPATH + "Gif/attr.gif"
Attr470.altTxt = "Column"
Attr453 = insDoc(Tbl39, gLnk("R", "name_en", "Model8/Tbl39_Attr.htm#Attr453"))
Attr453.iconSrc = ICONPATH + "Gif/attr.gif"
Attr453.altTxt = "Column"
Attr466 = insDoc(Tbl39, gLnk("R", "name_cn", "Model8/Tbl39_Attr.htm#Attr466"))
Attr466.iconSrc = ICONPATH + "Gif/attr.gif"
Attr466.altTxt = "Column"
Attr454 = insDoc(Tbl39, gLnk("R", "market_type", "Model8/Tbl39_Attr.htm#Attr454"))
Attr454.iconSrc = ICONPATH + "Gif/attr.gif"
Attr454.altTxt = "Column"
Attr463 = insDoc(Tbl39, gLnk("R", "area_id", "Model8/Tbl39_Attr.htm#Attr463"))
Attr463.iconSrc = ICONPATH + "Gif/attr.gif"
Attr463.altTxt = "Column"
Attr455 = insDoc(Tbl39, gLnk("R", "lon", "Model8/Tbl39_Attr.htm#Attr455"))
Attr455.iconSrc = ICONPATH + "Gif/attr.gif"
Attr455.altTxt = "Column"
Attr456 = insDoc(Tbl39, gLnk("R", "lat", "Model8/Tbl39_Attr.htm#Attr456"))
Attr456.iconSrc = ICONPATH + "Gif/attr.gif"
Attr456.altTxt = "Column"
Attr465 = insDoc(Tbl39, gLnk("R", "address", "Model8/Tbl39_Attr.htm#Attr465"))
Attr465.iconSrc = ICONPATH + "Gif/attr.gif"
Attr465.altTxt = "Column"
Attr467 = insDoc(Tbl39, gLnk("R", "description_en", "Model8/Tbl39_Attr.htm#Attr467"))
Attr467.iconSrc = ICONPATH + "Gif/attr.gif"
Attr467.altTxt = "Column"
Attr468 = insDoc(Tbl39, gLnk("R", "description_cn", "Model8/Tbl39_Attr.htm#Attr468"))
Attr468.iconSrc = ICONPATH + "Gif/attr.gif"
Attr468.altTxt = "Column"
Attr457 = insDoc(Tbl39, gLnk("R", "status", "Model8/Tbl39_Attr.htm#Attr457"))
Attr457.iconSrc = ICONPATH + "Gif/attr.gif"
Attr457.altTxt = "Column"
Attr469 = insDoc(Tbl39, gLnk("R", "sort", "Model8/Tbl39_Attr.htm#Attr469"))
Attr469.iconSrc = ICONPATH + "Gif/attr.gif"
Attr469.altTxt = "Column"
Attr464 = insDoc(Tbl39, gLnk("R", "is_delete", "Model8/Tbl39_Attr.htm#Attr464"))
Attr464.iconSrc = ICONPATH + "Gif/attr.gif"
Attr464.altTxt = "Column"
Attr458 = insDoc(Tbl39, gLnk("R", "remark", "Model8/Tbl39_Attr.htm#Attr458"))
Attr458.iconSrc = ICONPATH + "Gif/attr.gif"
Attr458.altTxt = "Column"
Attr459 = insDoc(Tbl39, gLnk("R", "create_by", "Model8/Tbl39_Attr.htm#Attr459"))
Attr459.iconSrc = ICONPATH + "Gif/attr.gif"
Attr459.altTxt = "Column"
Attr460 = insDoc(Tbl39, gLnk("R", "craete_date", "Model8/Tbl39_Attr.htm#Attr460"))
Attr460.iconSrc = ICONPATH + "Gif/attr.gif"
Attr460.altTxt = "Column"
Attr461 = insDoc(Tbl39, gLnk("R", "update_by", "Model8/Tbl39_Attr.htm#Attr461"))
Attr461.iconSrc = ICONPATH + "Gif/attr.gif"
Attr461.altTxt = "Column"
Attr462 = insDoc(Tbl39, gLnk("R", "update_date", "Model8/Tbl39_Attr.htm#Attr462"))
Attr462.iconSrc = ICONPATH + "Gif/attr.gif"
Attr462.altTxt = "Column"
}
Tbl50 = insFld(EntityFolder, gFld("bus_order", "Model8/Tbl50.htm"))
Tbl50.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl50.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr584 = insDoc(Tbl50, gLnk("R", "id", "Model8/Tbl50_Attr.htm#Attr584"))
Attr584.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr584.altTxt = "Primary Key"
Attr591 = insDoc(Tbl50, gLnk("R", "order_status", "Model8/Tbl50_Attr.htm#Attr591"))
Attr591.iconSrc = ICONPATH + "Gif/attr.gif"
Attr591.altTxt = "Column"
Attr592 = insDoc(Tbl50, gLnk("R", "payment_status", "Model8/Tbl50_Attr.htm#Attr592"))
Attr592.iconSrc = ICONPATH + "Gif/attr.gif"
Attr592.altTxt = "Column"
Attr600 = insDoc(Tbl50, gLnk("R", "market_id", "Model8/Tbl50_Attr.htm#Attr600"))
Attr600.iconSrc = ICONPATH + "Gif/attr.gif"
Attr600.altTxt = "Column"
Attr594 = insDoc(Tbl50, gLnk("R", "user_id", "Model8/Tbl50_Attr.htm#Attr594"))
Attr594.iconSrc = ICONPATH + "Gif/attr.gif"
Attr594.altTxt = "Column"
Attr593 = insDoc(Tbl50, gLnk("R", "dilivery_user_id", "Model8/Tbl50_Attr.htm#Attr593"))
Attr593.iconSrc = ICONPATH + "Gif/attr.gif"
Attr593.altTxt = "Column"
Attr595 = insDoc(Tbl50, gLnk("R", "pickup_address_id", "Model8/Tbl50_Attr.htm#Attr595"))
Attr595.iconSrc = ICONPATH + "Gif/attr.gif"
Attr595.altTxt = "Column"
Attr596 = insDoc(Tbl50, gLnk("R", "consignee_name", "Model8/Tbl50_Attr.htm#Attr596"))
Attr596.iconSrc = ICONPATH + "Gif/attr.gif"
Attr596.altTxt = "Column"
Attr597 = insDoc(Tbl50, gLnk("R", "consignee_phone", "Model8/Tbl50_Attr.htm#Attr597"))
Attr597.iconSrc = ICONPATH + "Gif/attr.gif"
Attr597.altTxt = "Column"
Attr598 = insDoc(Tbl50, gLnk("R", "total_plan_price", "Model8/Tbl50_Attr.htm#Attr598"))
Attr598.iconSrc = ICONPATH + "Gif/attr.gif"
Attr598.altTxt = "Column"
Attr599 = insDoc(Tbl50, gLnk("R", "total_real_price", "Model8/Tbl50_Attr.htm#Attr599"))
Attr599.iconSrc = ICONPATH + "Gif/attr.gif"
Attr599.altTxt = "Column"
Attr601 = insDoc(Tbl50, gLnk("R", "meal_num", "Model8/Tbl50_Attr.htm#Attr601"))
Attr601.iconSrc = ICONPATH + "Gif/attr.gif"
Attr601.altTxt = "Column"
Attr585 = insDoc(Tbl50, gLnk("R", "is_delete", "Model8/Tbl50_Attr.htm#Attr585"))
Attr585.iconSrc = ICONPATH + "Gif/attr.gif"
Attr585.altTxt = "Column"
Attr586 = insDoc(Tbl50, gLnk("R", "remark", "Model8/Tbl50_Attr.htm#Attr586"))
Attr586.iconSrc = ICONPATH + "Gif/attr.gif"
Attr586.altTxt = "Column"
Attr587 = insDoc(Tbl50, gLnk("R", "create_by", "Model8/Tbl50_Attr.htm#Attr587"))
Attr587.iconSrc = ICONPATH + "Gif/attr.gif"
Attr587.altTxt = "Column"
Attr588 = insDoc(Tbl50, gLnk("R", "create_date", "Model8/Tbl50_Attr.htm#Attr588"))
Attr588.iconSrc = ICONPATH + "Gif/attr.gif"
Attr588.altTxt = "Column"
Attr589 = insDoc(Tbl50, gLnk("R", "update_by", "Model8/Tbl50_Attr.htm#Attr589"))
Attr589.iconSrc = ICONPATH + "Gif/attr.gif"
Attr589.altTxt = "Column"
Attr590 = insDoc(Tbl50, gLnk("R", "update_date", "Model8/Tbl50_Attr.htm#Attr590"))
Attr590.iconSrc = ICONPATH + "Gif/attr.gif"
Attr590.altTxt = "Column"
}
Tbl52 = insFld(EntityFolder, gFld("bus_order_dish", "Model8/Tbl52.htm"))
Tbl52.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl52.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr614 = insDoc(Tbl52, gLnk("R", "id", "Model8/Tbl52_Attr.htm#Attr614"))
Attr614.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr614.altTxt = "Primary Key"
Attr615 = insDoc(Tbl52, gLnk("R", "order_id", "Model8/Tbl52_Attr.htm#Attr615"))
Attr615.iconSrc = ICONPATH + "Gif/attr.gif"
Attr615.altTxt = "Column"
Attr616 = insDoc(Tbl52, gLnk("R", "dish_id", "Model8/Tbl52_Attr.htm#Attr616"))
Attr616.iconSrc = ICONPATH + "Gif/attr.gif"
Attr616.altTxt = "Column"
Attr617 = insDoc(Tbl52, gLnk("R", "total_original_price", "Model8/Tbl52_Attr.htm#Attr617"))
Attr617.iconSrc = ICONPATH + "Gif/attr.gif"
Attr617.altTxt = "Column"
Attr626 = insDoc(Tbl52, gLnk("R", "total_discount_price", "Model8/Tbl52_Attr.htm#Attr626"))
Attr626.iconSrc = ICONPATH + "Gif/attr.gif"
Attr626.altTxt = "Column"
Attr625 = insDoc(Tbl52, gLnk("R", "unit_original_price", "Model8/Tbl52_Attr.htm#Attr625"))
Attr625.iconSrc = ICONPATH + "Gif/attr.gif"
Attr625.altTxt = "Column"
Attr627 = insDoc(Tbl52, gLnk("R", "unit_discount_price", "Model8/Tbl52_Attr.htm#Attr627"))
Attr627.iconSrc = ICONPATH + "Gif/attr.gif"
Attr627.altTxt = "Column"
Attr624 = insDoc(Tbl52, gLnk("R", "count", "Model8/Tbl52_Attr.htm#Attr624"))
Attr624.iconSrc = ICONPATH + "Gif/attr.gif"
Attr624.altTxt = "Column"
Attr618 = insDoc(Tbl52, gLnk("R", "is_delete", "Model8/Tbl52_Attr.htm#Attr618"))
Attr618.iconSrc = ICONPATH + "Gif/attr.gif"
Attr618.altTxt = "Column"
Attr619 = insDoc(Tbl52, gLnk("R", "remark", "Model8/Tbl52_Attr.htm#Attr619"))
Attr619.iconSrc = ICONPATH + "Gif/attr.gif"
Attr619.altTxt = "Column"
Attr620 = insDoc(Tbl52, gLnk("R", "create_by", "Model8/Tbl52_Attr.htm#Attr620"))
Attr620.iconSrc = ICONPATH + "Gif/attr.gif"
Attr620.altTxt = "Column"
Attr621 = insDoc(Tbl52, gLnk("R", "create_date", "Model8/Tbl52_Attr.htm#Attr621"))
Attr621.iconSrc = ICONPATH + "Gif/attr.gif"
Attr621.altTxt = "Column"
Attr622 = insDoc(Tbl52, gLnk("R", "update_by", "Model8/Tbl52_Attr.htm#Attr622"))
Attr622.iconSrc = ICONPATH + "Gif/attr.gif"
Attr622.altTxt = "Column"
Attr623 = insDoc(Tbl52, gLnk("R", "update_date", "Model8/Tbl52_Attr.htm#Attr623"))
Attr623.iconSrc = ICONPATH + "Gif/attr.gif"
Attr623.altTxt = "Column"
}
Tbl53 = insFld(EntityFolder, gFld("bus_payment", "Model8/Tbl53.htm"))
Tbl53.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl53.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr628 = insDoc(Tbl53, gLnk("R", "id", "Model8/Tbl53_Attr.htm#Attr628"))
Attr628.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr628.altTxt = "Primary Key"
Attr629 = insDoc(Tbl53, gLnk("R", "payment_channel", "Model8/Tbl53_Attr.htm#Attr629"))
Attr629.iconSrc = ICONPATH + "Gif/attr.gif"
Attr629.altTxt = "Column"
Attr639 = insDoc(Tbl53, gLnk("R", "payment_type", "Model8/Tbl53_Attr.htm#Attr639"))
Attr639.iconSrc = ICONPATH + "Gif/attr.gif"
Attr639.altTxt = "Column"
Attr630 = insDoc(Tbl53, gLnk("R", "amount", "Model8/Tbl53_Attr.htm#Attr630"))
Attr630.iconSrc = ICONPATH + "Gif/attr.gif"
Attr630.altTxt = "Column"
Attr631 = insDoc(Tbl53, gLnk("R", "order_id", "Model8/Tbl53_Attr.htm#Attr631"))
Attr631.iconSrc = ICONPATH + "Gif/attr.gif"
Attr631.altTxt = "Column"
Attr632 = insDoc(Tbl53, gLnk("R", "user_id", "Model8/Tbl53_Attr.htm#Attr632"))
Attr632.iconSrc = ICONPATH + "Gif/attr.gif"
Attr632.altTxt = "Column"
Attr640 = insDoc(Tbl53, gLnk("R", "correlation_code", "Model8/Tbl53_Attr.htm#Attr640"))
Attr640.iconSrc = ICONPATH + "Gif/attr.gif"
Attr640.altTxt = "Column"
Attr633 = insDoc(Tbl53, gLnk("R", "is_delete", "Model8/Tbl53_Attr.htm#Attr633"))
Attr633.iconSrc = ICONPATH + "Gif/attr.gif"
Attr633.altTxt = "Column"
Attr634 = insDoc(Tbl53, gLnk("R", "remark", "Model8/Tbl53_Attr.htm#Attr634"))
Attr634.iconSrc = ICONPATH + "Gif/attr.gif"
Attr634.altTxt = "Column"
Attr635 = insDoc(Tbl53, gLnk("R", "create_by", "Model8/Tbl53_Attr.htm#Attr635"))
Attr635.iconSrc = ICONPATH + "Gif/attr.gif"
Attr635.altTxt = "Column"
Attr636 = insDoc(Tbl53, gLnk("R", "create_date", "Model8/Tbl53_Attr.htm#Attr636"))
Attr636.iconSrc = ICONPATH + "Gif/attr.gif"
Attr636.altTxt = "Column"
Attr637 = insDoc(Tbl53, gLnk("R", "update_by", "Model8/Tbl53_Attr.htm#Attr637"))
Attr637.iconSrc = ICONPATH + "Gif/attr.gif"
Attr637.altTxt = "Column"
Attr638 = insDoc(Tbl53, gLnk("R", "update_date", "Model8/Tbl53_Attr.htm#Attr638"))
Attr638.iconSrc = ICONPATH + "Gif/attr.gif"
Attr638.altTxt = "Column"
}
Tbl42 = insFld(EntityFolder, gFld("bus_pickup_address", "Model8/Tbl42.htm"))
Tbl42.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl42.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr499 = insDoc(Tbl42, gLnk("R", "id", "Model8/Tbl42_Attr.htm#Attr499"))
Attr499.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr499.altTxt = "Primary Key"
Attr513 = insDoc(Tbl42, gLnk("R", "pickup_code", "Model8/Tbl42_Attr.htm#Attr513"))
Attr513.iconSrc = ICONPATH + "Gif/attr.gif"
Attr513.altTxt = "Column"
Attr500 = insDoc(Tbl42, gLnk("R", "name", "Model8/Tbl42_Attr.htm#Attr500"))
Attr500.iconSrc = ICONPATH + "Gif/attr.gif"
Attr500.altTxt = "Column"
Attr501 = insDoc(Tbl42, gLnk("R", "address", "Model8/Tbl42_Attr.htm#Attr501"))
Attr501.iconSrc = ICONPATH + "Gif/attr.gif"
Attr501.altTxt = "Column"
Attr502 = insDoc(Tbl42, gLnk("R", "area_id", "Model8/Tbl42_Attr.htm#Attr502"))
Attr502.iconSrc = ICONPATH + "Gif/attr.gif"
Attr502.altTxt = "Column"
Attr503 = insDoc(Tbl42, gLnk("R", "lon", "Model8/Tbl42_Attr.htm#Attr503"))
Attr503.iconSrc = ICONPATH + "Gif/attr.gif"
Attr503.altTxt = "Column"
Attr504 = insDoc(Tbl42, gLnk("R", "lat", "Model8/Tbl42_Attr.htm#Attr504"))
Attr504.iconSrc = ICONPATH + "Gif/attr.gif"
Attr504.altTxt = "Column"
Attr505 = insDoc(Tbl42, gLnk("R", "status", "Model8/Tbl42_Attr.htm#Attr505"))
Attr505.iconSrc = ICONPATH + "Gif/attr.gif"
Attr505.altTxt = "Column"
Attr512 = insDoc(Tbl42, gLnk("R", "sort", "Model8/Tbl42_Attr.htm#Attr512"))
Attr512.iconSrc = ICONPATH + "Gif/attr.gif"
Attr512.altTxt = "Column"
Attr506 = insDoc(Tbl42, gLnk("R", "is_delete", "Model8/Tbl42_Attr.htm#Attr506"))
Attr506.iconSrc = ICONPATH + "Gif/attr.gif"
Attr506.altTxt = "Column"
Attr507 = insDoc(Tbl42, gLnk("R", "remark", "Model8/Tbl42_Attr.htm#Attr507"))
Attr507.iconSrc = ICONPATH + "Gif/attr.gif"
Attr507.altTxt = "Column"
Attr508 = insDoc(Tbl42, gLnk("R", "create_by", "Model8/Tbl42_Attr.htm#Attr508"))
Attr508.iconSrc = ICONPATH + "Gif/attr.gif"
Attr508.altTxt = "Column"
Attr509 = insDoc(Tbl42, gLnk("R", "create_date", "Model8/Tbl42_Attr.htm#Attr509"))
Attr509.iconSrc = ICONPATH + "Gif/attr.gif"
Attr509.altTxt = "Column"
Attr510 = insDoc(Tbl42, gLnk("R", "update_by", "Model8/Tbl42_Attr.htm#Attr510"))
Attr510.iconSrc = ICONPATH + "Gif/attr.gif"
Attr510.altTxt = "Column"
Attr511 = insDoc(Tbl42, gLnk("R", "update_date", "Model8/Tbl42_Attr.htm#Attr511"))
Attr511.iconSrc = ICONPATH + "Gif/attr.gif"
Attr511.altTxt = "Column"
}
Tbl44 = insFld(EntityFolder, gFld("bus_pickup_market", "Model8/Tbl44.htm"))
Tbl44.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl44.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr523 = insDoc(Tbl44, gLnk("R", "id", "Model8/Tbl44_Attr.htm#Attr523"))
Attr523.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr523.altTxt = "Primary Key"
Attr524 = insDoc(Tbl44, gLnk("R", "pickup_address_id", "Model8/Tbl44_Attr.htm#Attr524"))
Attr524.iconSrc = ICONPATH + "Gif/attr.gif"
Attr524.altTxt = "Column"
Attr525 = insDoc(Tbl44, gLnk("R", "market_id", "Model8/Tbl44_Attr.htm#Attr525"))
Attr525.iconSrc = ICONPATH + "Gif/attr.gif"
Attr525.altTxt = "Column"
Attr526 = insDoc(Tbl44, gLnk("R", "is_delete", "Model8/Tbl44_Attr.htm#Attr526"))
Attr526.iconSrc = ICONPATH + "Gif/attr.gif"
Attr526.altTxt = "Column"
Attr527 = insDoc(Tbl44, gLnk("R", "remark", "Model8/Tbl44_Attr.htm#Attr527"))
Attr527.iconSrc = ICONPATH + "Gif/attr.gif"
Attr527.altTxt = "Column"
Attr528 = insDoc(Tbl44, gLnk("R", "create_by", "Model8/Tbl44_Attr.htm#Attr528"))
Attr528.iconSrc = ICONPATH + "Gif/attr.gif"
Attr528.altTxt = "Column"
Attr529 = insDoc(Tbl44, gLnk("R", "create_date", "Model8/Tbl44_Attr.htm#Attr529"))
Attr529.iconSrc = ICONPATH + "Gif/attr.gif"
Attr529.altTxt = "Column"
Attr530 = insDoc(Tbl44, gLnk("R", "update_by", "Model8/Tbl44_Attr.htm#Attr530"))
Attr530.iconSrc = ICONPATH + "Gif/attr.gif"
Attr530.altTxt = "Column"
Attr531 = insDoc(Tbl44, gLnk("R", "update_date", "Model8/Tbl44_Attr.htm#Attr531"))
Attr531.iconSrc = ICONPATH + "Gif/attr.gif"
Attr531.altTxt = "Column"
}
Tbl46 = insFld(EntityFolder, gFld("bus_pickup_times", "Model8/Tbl46.htm"))
Tbl46.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl46.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr541 = insDoc(Tbl46, gLnk("R", "id", "Model8/Tbl46_Attr.htm#Attr541"))
Attr541.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr541.altTxt = "Primary Key"
Attr542 = insDoc(Tbl46, gLnk("R", "pickup_address_id", "Model8/Tbl46_Attr.htm#Attr542"))
Attr542.iconSrc = ICONPATH + "Gif/attr.gif"
Attr542.altTxt = "Column"
Attr550 = insDoc(Tbl46, gLnk("R", "times_id", "Model8/Tbl46_Attr.htm#Attr550"))
Attr550.iconSrc = ICONPATH + "Gif/attr.gif"
Attr550.altTxt = "Column"
Attr543 = insDoc(Tbl46, gLnk("R", "dish_type", "Model8/Tbl46_Attr.htm#Attr543"))
Attr543.iconSrc = ICONPATH + "Gif/attr.gif"
Attr543.altTxt = "Column"
Attr544 = insDoc(Tbl46, gLnk("R", "is_delete", "Model8/Tbl46_Attr.htm#Attr544"))
Attr544.iconSrc = ICONPATH + "Gif/attr.gif"
Attr544.altTxt = "Column"
Attr545 = insDoc(Tbl46, gLnk("R", "remark", "Model8/Tbl46_Attr.htm#Attr545"))
Attr545.iconSrc = ICONPATH + "Gif/attr.gif"
Attr545.altTxt = "Column"
Attr546 = insDoc(Tbl46, gLnk("R", "create_by", "Model8/Tbl46_Attr.htm#Attr546"))
Attr546.iconSrc = ICONPATH + "Gif/attr.gif"
Attr546.altTxt = "Column"
Attr547 = insDoc(Tbl46, gLnk("R", "create_date", "Model8/Tbl46_Attr.htm#Attr547"))
Attr547.iconSrc = ICONPATH + "Gif/attr.gif"
Attr547.altTxt = "Column"
Attr548 = insDoc(Tbl46, gLnk("R", "update_by", "Model8/Tbl46_Attr.htm#Attr548"))
Attr548.iconSrc = ICONPATH + "Gif/attr.gif"
Attr548.altTxt = "Column"
Attr549 = insDoc(Tbl46, gLnk("R", "update_date", "Model8/Tbl46_Attr.htm#Attr549"))
Attr549.iconSrc = ICONPATH + "Gif/attr.gif"
Attr549.altTxt = "Column"
}
Tbl43 = insFld(EntityFolder, gFld("bus_pickup_user", "Model8/Tbl43.htm"))
Tbl43.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl43.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr514 = insDoc(Tbl43, gLnk("R", "id", "Model8/Tbl43_Attr.htm#Attr514"))
Attr514.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr514.altTxt = "Primary Key"
Attr515 = insDoc(Tbl43, gLnk("R", "pickup_address_id", "Model8/Tbl43_Attr.htm#Attr515"))
Attr515.iconSrc = ICONPATH + "Gif/attr.gif"
Attr515.altTxt = "Column"
Attr516 = insDoc(Tbl43, gLnk("R", "user_id", "Model8/Tbl43_Attr.htm#Attr516"))
Attr516.iconSrc = ICONPATH + "Gif/attr.gif"
Attr516.altTxt = "Column"
Attr517 = insDoc(Tbl43, gLnk("R", "is_delete", "Model8/Tbl43_Attr.htm#Attr517"))
Attr517.iconSrc = ICONPATH + "Gif/attr.gif"
Attr517.altTxt = "Column"
Attr518 = insDoc(Tbl43, gLnk("R", "remark", "Model8/Tbl43_Attr.htm#Attr518"))
Attr518.iconSrc = ICONPATH + "Gif/attr.gif"
Attr518.altTxt = "Column"
Attr519 = insDoc(Tbl43, gLnk("R", "create_by", "Model8/Tbl43_Attr.htm#Attr519"))
Attr519.iconSrc = ICONPATH + "Gif/attr.gif"
Attr519.altTxt = "Column"
Attr520 = insDoc(Tbl43, gLnk("R", "create_date", "Model8/Tbl43_Attr.htm#Attr520"))
Attr520.iconSrc = ICONPATH + "Gif/attr.gif"
Attr520.altTxt = "Column"
Attr521 = insDoc(Tbl43, gLnk("R", "update_by", "Model8/Tbl43_Attr.htm#Attr521"))
Attr521.iconSrc = ICONPATH + "Gif/attr.gif"
Attr521.altTxt = "Column"
Attr522 = insDoc(Tbl43, gLnk("R", "update_date", "Model8/Tbl43_Attr.htm#Attr522"))
Attr522.iconSrc = ICONPATH + "Gif/attr.gif"
Attr522.altTxt = "Column"
}
Tbl51 = insFld(EntityFolder, gFld("bus_share", "Model8/Tbl51.htm"))
Tbl51.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl51.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr602 = insDoc(Tbl51, gLnk("R", "id", "Model8/Tbl51_Attr.htm#Attr602"))
Attr602.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr602.altTxt = "Primary Key"
Attr603 = insDoc(Tbl51, gLnk("R", "bus_type", "Model8/Tbl51_Attr.htm#Attr603"))
Attr603.iconSrc = ICONPATH + "Gif/attr.gif"
Attr603.altTxt = "Column"
Attr604 = insDoc(Tbl51, gLnk("R", "title", "Model8/Tbl51_Attr.htm#Attr604"))
Attr604.iconSrc = ICONPATH + "Gif/attr.gif"
Attr604.altTxt = "Column"
Attr605 = insDoc(Tbl51, gLnk("R", "content", "Model8/Tbl51_Attr.htm#Attr605"))
Attr605.iconSrc = ICONPATH + "Gif/attr.gif"
Attr605.altTxt = "Column"
Attr606 = insDoc(Tbl51, gLnk("R", "link_url", "Model8/Tbl51_Attr.htm#Attr606"))
Attr606.iconSrc = ICONPATH + "Gif/attr.gif"
Attr606.altTxt = "Column"
Attr607 = insDoc(Tbl51, gLnk("R", "pic_url", "Model8/Tbl51_Attr.htm#Attr607"))
Attr607.iconSrc = ICONPATH + "Gif/attr.gif"
Attr607.altTxt = "Column"
Attr608 = insDoc(Tbl51, gLnk("R", "is_delete", "Model8/Tbl51_Attr.htm#Attr608"))
Attr608.iconSrc = ICONPATH + "Gif/attr.gif"
Attr608.altTxt = "Column"
Attr609 = insDoc(Tbl51, gLnk("R", "remark", "Model8/Tbl51_Attr.htm#Attr609"))
Attr609.iconSrc = ICONPATH + "Gif/attr.gif"
Attr609.altTxt = "Column"
Attr610 = insDoc(Tbl51, gLnk("R", "create_by", "Model8/Tbl51_Attr.htm#Attr610"))
Attr610.iconSrc = ICONPATH + "Gif/attr.gif"
Attr610.altTxt = "Column"
Attr611 = insDoc(Tbl51, gLnk("R", "create_date", "Model8/Tbl51_Attr.htm#Attr611"))
Attr611.iconSrc = ICONPATH + "Gif/attr.gif"
Attr611.altTxt = "Column"
Attr612 = insDoc(Tbl51, gLnk("R", "update_by", "Model8/Tbl51_Attr.htm#Attr612"))
Attr612.iconSrc = ICONPATH + "Gif/attr.gif"
Attr612.altTxt = "Column"
Attr613 = insDoc(Tbl51, gLnk("R", "update_date", "Model8/Tbl51_Attr.htm#Attr613"))
Attr613.iconSrc = ICONPATH + "Gif/attr.gif"
Attr613.altTxt = "Column"
}
Tbl49 = insFld(EntityFolder, gFld("bus_times", "Model8/Tbl49.htm"))
Tbl49.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl49.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr575 = insDoc(Tbl49, gLnk("R", "id", "Model8/Tbl49_Attr.htm#Attr575"))
Attr575.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr575.altTxt = "Primary Key"
Attr576 = insDoc(Tbl49, gLnk("R", "start_time", "Model8/Tbl49_Attr.htm#Attr576"))
Attr576.iconSrc = ICONPATH + "Gif/attr.gif"
Attr576.altTxt = "Column"
Attr577 = insDoc(Tbl49, gLnk("R", "end_time", "Model8/Tbl49_Attr.htm#Attr577"))
Attr577.iconSrc = ICONPATH + "Gif/attr.gif"
Attr577.altTxt = "Column"
Attr578 = insDoc(Tbl49, gLnk("R", "is_delete", "Model8/Tbl49_Attr.htm#Attr578"))
Attr578.iconSrc = ICONPATH + "Gif/attr.gif"
Attr578.altTxt = "Column"
Attr579 = insDoc(Tbl49, gLnk("R", "remark", "Model8/Tbl49_Attr.htm#Attr579"))
Attr579.iconSrc = ICONPATH + "Gif/attr.gif"
Attr579.altTxt = "Column"
Attr580 = insDoc(Tbl49, gLnk("R", "create_by", "Model8/Tbl49_Attr.htm#Attr580"))
Attr580.iconSrc = ICONPATH + "Gif/attr.gif"
Attr580.altTxt = "Column"
Attr581 = insDoc(Tbl49, gLnk("R", "create_date", "Model8/Tbl49_Attr.htm#Attr581"))
Attr581.iconSrc = ICONPATH + "Gif/attr.gif"
Attr581.altTxt = "Column"
Attr582 = insDoc(Tbl49, gLnk("R", "update_by", "Model8/Tbl49_Attr.htm#Attr582"))
Attr582.iconSrc = ICONPATH + "Gif/attr.gif"
Attr582.altTxt = "Column"
Attr583 = insDoc(Tbl49, gLnk("R", "update_date", "Model8/Tbl49_Attr.htm#Attr583"))
Attr583.iconSrc = ICONPATH + "Gif/attr.gif"
Attr583.altTxt = "Column"
}
Tbl37 = insFld(EntityFolder, gFld("bus_user", "Model8/Tbl37.htm"))
Tbl37.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl37.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr424 = insDoc(Tbl37, gLnk("R", "id", "Model8/Tbl37_Attr.htm#Attr424"))
Attr424.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr424.altTxt = "Primary Key"
Attr437 = insDoc(Tbl37, gLnk("R", "user_type", "Model8/Tbl37_Attr.htm#Attr437"))
Attr437.iconSrc = ICONPATH + "Gif/attr.gif"
Attr437.altTxt = "Column"
Attr425 = insDoc(Tbl37, gLnk("R", "pwd", "Model8/Tbl37_Attr.htm#Attr425"))
Attr425.iconSrc = ICONPATH + "Gif/attr.gif"
Attr425.altTxt = "Column"
Attr426 = insDoc(Tbl37, gLnk("R", "nickname", "Model8/Tbl37_Attr.htm#Attr426"))
Attr426.iconSrc = ICONPATH + "Gif/attr.gif"
Attr426.altTxt = "Column"
Attr435 = insDoc(Tbl37, gLnk("R", "phone_num", "Model8/Tbl37_Attr.htm#Attr435"))
Attr435.iconSrc = ICONPATH + "Gif/attr.gif"
Attr435.altTxt = "Column"
Attr436 = insDoc(Tbl37, gLnk("R", "pic_url", "Model8/Tbl37_Attr.htm#Attr436"))
Attr436.iconSrc = ICONPATH + "Gif/attr.gif"
Attr436.altTxt = "Column"
Attr427 = insDoc(Tbl37, gLnk("R", "sex", "Model8/Tbl37_Attr.htm#Attr427"))
Attr427.iconSrc = ICONPATH + "Gif/attr.gif"
Attr427.altTxt = "Column"
Attr428 = insDoc(Tbl37, gLnk("R", "code", "Model8/Tbl37_Attr.htm#Attr428"))
Attr428.iconSrc = ICONPATH + "Gif/attr.gif"
Attr428.altTxt = "Column"
Attr438 = insDoc(Tbl37, gLnk("R", "generate_time", "Model8/Tbl37_Attr.htm#Attr438"))
Attr438.iconSrc = ICONPATH + "Gif/attr.gif"
Attr438.altTxt = "Column"
Attr439 = insDoc(Tbl37, gLnk("R", "cur_deviceId", "Model8/Tbl37_Attr.htm#Attr439"))
Attr439.iconSrc = ICONPATH + "Gif/attr.gif"
Attr439.altTxt = "Column"
Attr434 = insDoc(Tbl37, gLnk("R", "is_delete", "Model8/Tbl37_Attr.htm#Attr434"))
Attr434.iconSrc = ICONPATH + "Gif/attr.gif"
Attr434.altTxt = "Column"
Attr429 = insDoc(Tbl37, gLnk("R", "remark", "Model8/Tbl37_Attr.htm#Attr429"))
Attr429.iconSrc = ICONPATH + "Gif/attr.gif"
Attr429.altTxt = "Column"
Attr430 = insDoc(Tbl37, gLnk("R", "create_by", "Model8/Tbl37_Attr.htm#Attr430"))
Attr430.iconSrc = ICONPATH + "Gif/attr.gif"
Attr430.altTxt = "Column"
Attr431 = insDoc(Tbl37, gLnk("R", "create_date", "Model8/Tbl37_Attr.htm#Attr431"))
Attr431.iconSrc = ICONPATH + "Gif/attr.gif"
Attr431.altTxt = "Column"
Attr432 = insDoc(Tbl37, gLnk("R", "update_by", "Model8/Tbl37_Attr.htm#Attr432"))
Attr432.iconSrc = ICONPATH + "Gif/attr.gif"
Attr432.altTxt = "Column"
Attr433 = insDoc(Tbl37, gLnk("R", "update_date", "Model8/Tbl37_Attr.htm#Attr433"))
Attr433.iconSrc = ICONPATH + "Gif/attr.gif"
Attr433.altTxt = "Column"
}
Tbl45 = insFld(EntityFolder, gFld("bus_user_black_list", "Model8/Tbl45.htm"))
Tbl45.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl45.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr532 = insDoc(Tbl45, gLnk("R", "id", "Model8/Tbl45_Attr.htm#Attr532"))
Attr532.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr532.altTxt = "Primary Key"
Attr533 = insDoc(Tbl45, gLnk("R", "user_type", "Model8/Tbl45_Attr.htm#Attr533"))
Attr533.iconSrc = ICONPATH + "Gif/attr.gif"
Attr533.altTxt = "Column"
Attr534 = insDoc(Tbl45, gLnk("R", "phone_num", "Model8/Tbl45_Attr.htm#Attr534"))
Attr534.iconSrc = ICONPATH + "Gif/attr.gif"
Attr534.altTxt = "Column"
Attr535 = insDoc(Tbl45, gLnk("R", "is_delete", "Model8/Tbl45_Attr.htm#Attr535"))
Attr535.iconSrc = ICONPATH + "Gif/attr.gif"
Attr535.altTxt = "Column"
Attr536 = insDoc(Tbl45, gLnk("R", "remark", "Model8/Tbl45_Attr.htm#Attr536"))
Attr536.iconSrc = ICONPATH + "Gif/attr.gif"
Attr536.altTxt = "Column"
Attr537 = insDoc(Tbl45, gLnk("R", "create_by", "Model8/Tbl45_Attr.htm#Attr537"))
Attr537.iconSrc = ICONPATH + "Gif/attr.gif"
Attr537.altTxt = "Column"
Attr538 = insDoc(Tbl45, gLnk("R", "create_date", "Model8/Tbl45_Attr.htm#Attr538"))
Attr538.iconSrc = ICONPATH + "Gif/attr.gif"
Attr538.altTxt = "Column"
Attr539 = insDoc(Tbl45, gLnk("R", "update_by", "Model8/Tbl45_Attr.htm#Attr539"))
Attr539.iconSrc = ICONPATH + "Gif/attr.gif"
Attr539.altTxt = "Column"
Attr540 = insDoc(Tbl45, gLnk("R", "update_date", "Model8/Tbl45_Attr.htm#Attr540"))
Attr540.iconSrc = ICONPATH + "Gif/attr.gif"
Attr540.altTxt = "Column"
}
Tbl47 = insFld(EntityFolder, gFld("bus_user_device", "Model8/Tbl47.htm"))
Tbl47.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl47.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr551 = insDoc(Tbl47, gLnk("R", "id", "Model8/Tbl47_Attr.htm#Attr551"))
Attr551.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr551.altTxt = "Primary Key"
Attr552 = insDoc(Tbl47, gLnk("R", "user_id", "Model8/Tbl47_Attr.htm#Attr552"))
Attr552.iconSrc = ICONPATH + "Gif/attr.gif"
Attr552.altTxt = "Column"
Attr553 = insDoc(Tbl47, gLnk("R", "phone_num", "Model8/Tbl47_Attr.htm#Attr553"))
Attr553.iconSrc = ICONPATH + "Gif/attr.gif"
Attr553.altTxt = "Column"
Attr562 = insDoc(Tbl47, gLnk("R", "device_id", "Model8/Tbl47_Attr.htm#Attr562"))
Attr562.iconSrc = ICONPATH + "Gif/attr.gif"
Attr562.altTxt = "Column"
Attr563 = insDoc(Tbl47, gLnk("R", "device_type", "Model8/Tbl47_Attr.htm#Attr563"))
Attr563.iconSrc = ICONPATH + "Gif/attr.gif"
Attr563.altTxt = "Column"
Attr554 = insDoc(Tbl47, gLnk("R", "pushToken", "Model8/Tbl47_Attr.htm#Attr554"))
Attr554.iconSrc = ICONPATH + "Gif/attr.gif"
Attr554.altTxt = "Column"
Attr555 = insDoc(Tbl47, gLnk("R", "app_version", "Model8/Tbl47_Attr.htm#Attr555"))
Attr555.iconSrc = ICONPATH + "Gif/attr.gif"
Attr555.altTxt = "Column"
Attr556 = insDoc(Tbl47, gLnk("R", "is_delete", "Model8/Tbl47_Attr.htm#Attr556"))
Attr556.iconSrc = ICONPATH + "Gif/attr.gif"
Attr556.altTxt = "Column"
Attr557 = insDoc(Tbl47, gLnk("R", "remark", "Model8/Tbl47_Attr.htm#Attr557"))
Attr557.iconSrc = ICONPATH + "Gif/attr.gif"
Attr557.altTxt = "Column"
Attr558 = insDoc(Tbl47, gLnk("R", "create_by", "Model8/Tbl47_Attr.htm#Attr558"))
Attr558.iconSrc = ICONPATH + "Gif/attr.gif"
Attr558.altTxt = "Column"
Attr559 = insDoc(Tbl47, gLnk("R", "create_date", "Model8/Tbl47_Attr.htm#Attr559"))
Attr559.iconSrc = ICONPATH + "Gif/attr.gif"
Attr559.altTxt = "Column"
Attr560 = insDoc(Tbl47, gLnk("R", "update_by", "Model8/Tbl47_Attr.htm#Attr560"))
Attr560.iconSrc = ICONPATH + "Gif/attr.gif"
Attr560.altTxt = "Column"
Attr561 = insDoc(Tbl47, gLnk("R", "update_date", "Model8/Tbl47_Attr.htm#Attr561"))
Attr561.iconSrc = ICONPATH + "Gif/attr.gif"
Attr561.altTxt = "Column"
}
Tbl54 = insFld(EntityFolder, gFld("bus_wx_user", "Model8/Tbl54.htm"))
Tbl54.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl54.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr641 = insDoc(Tbl54, gLnk("R", "id", "Model8/Tbl54_Attr.htm#Attr641"))
Attr641.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr641.altTxt = "Primary Key"
Attr642 = insDoc(Tbl54, gLnk("R", "user_id", "Model8/Tbl54_Attr.htm#Attr642"))
Attr642.iconSrc = ICONPATH + "Gif/attr.gif"
Attr642.altTxt = "Column"
Attr643 = insDoc(Tbl54, gLnk("R", "access_token", "Model8/Tbl54_Attr.htm#Attr643"))
Attr643.iconSrc = ICONPATH + "Gif/attr.gif"
Attr643.altTxt = "Column"
Attr644 = insDoc(Tbl54, gLnk("R", "expires_in", "Model8/Tbl54_Attr.htm#Attr644"))
Attr644.iconSrc = ICONPATH + "Gif/attr.gif"
Attr644.altTxt = "Column"
Attr645 = insDoc(Tbl54, gLnk("R", "refresh_token", "Model8/Tbl54_Attr.htm#Attr645"))
Attr645.iconSrc = ICONPATH + "Gif/attr.gif"
Attr645.altTxt = "Column"
Attr646 = insDoc(Tbl54, gLnk("R", "open_id", "Model8/Tbl54_Attr.htm#Attr646"))
Attr646.iconSrc = ICONPATH + "Gif/attr.gif"
Attr646.altTxt = "Column"
Attr647 = insDoc(Tbl54, gLnk("R", "scope", "Model8/Tbl54_Attr.htm#Attr647"))
Attr647.iconSrc = ICONPATH + "Gif/attr.gif"
Attr647.altTxt = "Column"
Attr648 = insDoc(Tbl54, gLnk("R", "remark", "Model8/Tbl54_Attr.htm#Attr648"))
Attr648.iconSrc = ICONPATH + "Gif/attr.gif"
Attr648.altTxt = "Column"
Attr649 = insDoc(Tbl54, gLnk("R", "create_by", "Model8/Tbl54_Attr.htm#Attr649"))
Attr649.iconSrc = ICONPATH + "Gif/attr.gif"
Attr649.altTxt = "Column"
Attr650 = insDoc(Tbl54, gLnk("R", "create_date", "Model8/Tbl54_Attr.htm#Attr650"))
Attr650.iconSrc = ICONPATH + "Gif/attr.gif"
Attr650.altTxt = "Column"
Attr651 = insDoc(Tbl54, gLnk("R", "update_by", "Model8/Tbl54_Attr.htm#Attr651"))
Attr651.iconSrc = ICONPATH + "Gif/attr.gif"
Attr651.altTxt = "Column"
Attr652 = insDoc(Tbl54, gLnk("R", "update_date", "Model8/Tbl54_Attr.htm#Attr652"))
Attr652.iconSrc = ICONPATH + "Gif/attr.gif"
Attr652.altTxt = "Column"
}
Tbl35 = insFld(EntityFolder, gFld("sys_constant", "Model8/Tbl35.htm"))
Tbl35.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl35.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr408 = insDoc(Tbl35, gLnk("R", "id", "Model8/Tbl35_Attr.htm#Attr408"))
Attr408.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr408.altTxt = "Primary Key"
Attr414 = insDoc(Tbl35, gLnk("R", "name", "Model8/Tbl35_Attr.htm#Attr414"))
Attr414.iconSrc = ICONPATH + "Gif/attr.gif"
Attr414.altTxt = "Column"
Attr409 = insDoc(Tbl35, gLnk("R", "remark", "Model8/Tbl35_Attr.htm#Attr409"))
Attr409.iconSrc = ICONPATH + "Gif/attr.gif"
Attr409.altTxt = "Column"
Attr410 = insDoc(Tbl35, gLnk("R", "create_by", "Model8/Tbl35_Attr.htm#Attr410"))
Attr410.iconSrc = ICONPATH + "Gif/attr.gif"
Attr410.altTxt = "Column"
Attr411 = insDoc(Tbl35, gLnk("R", "create_date", "Model8/Tbl35_Attr.htm#Attr411"))
Attr411.iconSrc = ICONPATH + "Gif/attr.gif"
Attr411.altTxt = "Column"
Attr412 = insDoc(Tbl35, gLnk("R", "update_by", "Model8/Tbl35_Attr.htm#Attr412"))
Attr412.iconSrc = ICONPATH + "Gif/attr.gif"
Attr412.altTxt = "Column"
Attr413 = insDoc(Tbl35, gLnk("R", "update_date", "Model8/Tbl35_Attr.htm#Attr413"))
Attr413.iconSrc = ICONPATH + "Gif/attr.gif"
Attr413.altTxt = "Column"
}
Tbl36 = insFld(EntityFolder, gFld("sys_constant_detail", "Model8/Tbl36.htm"))
Tbl36.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl36.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr415 = insDoc(Tbl36, gLnk("R", "id", "Model8/Tbl36_Attr.htm#Attr415"))
Attr415.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr415.altTxt = "Primary Key"
Attr421 = insDoc(Tbl36, gLnk("R", "constant_id", "Model8/Tbl36_Attr.htm#Attr421"))
Attr421.iconSrc = ICONPATH + "Gif/attr.gif"
Attr421.altTxt = "Column"
Attr422 = insDoc(Tbl36, gLnk("R", "constant_key", "Model8/Tbl36_Attr.htm#Attr422"))
Attr422.iconSrc = ICONPATH + "Gif/attr.gif"
Attr422.altTxt = "Column"
Attr423 = insDoc(Tbl36, gLnk("R", "constant_value", "Model8/Tbl36_Attr.htm#Attr423"))
Attr423.iconSrc = ICONPATH + "Gif/attr.gif"
Attr423.altTxt = "Column"
Attr416 = insDoc(Tbl36, gLnk("R", "remark", "Model8/Tbl36_Attr.htm#Attr416"))
Attr416.iconSrc = ICONPATH + "Gif/attr.gif"
Attr416.altTxt = "Column"
Attr417 = insDoc(Tbl36, gLnk("R", "create_by", "Model8/Tbl36_Attr.htm#Attr417"))
Attr417.iconSrc = ICONPATH + "Gif/attr.gif"
Attr417.altTxt = "Column"
Attr418 = insDoc(Tbl36, gLnk("R", "create_date", "Model8/Tbl36_Attr.htm#Attr418"))
Attr418.iconSrc = ICONPATH + "Gif/attr.gif"
Attr418.altTxt = "Column"
Attr419 = insDoc(Tbl36, gLnk("R", "update_by", "Model8/Tbl36_Attr.htm#Attr419"))
Attr419.iconSrc = ICONPATH + "Gif/attr.gif"
Attr419.altTxt = "Column"
Attr420 = insDoc(Tbl36, gLnk("R", "update_date", "Model8/Tbl36_Attr.htm#Attr420"))
Attr420.iconSrc = ICONPATH + "Gif/attr.gif"
Attr420.altTxt = "Column"
}
Tbl34 = insFld(EntityFolder, gFld("sys_user", "Model8/Tbl34.htm"))
Tbl34.iconSrc = ICONPATH + "Gif/entity.gif"
Tbl34.iconSrcClosed = ICONPATH + "Gif/entity.gif"
{
Attr397 = insDoc(Tbl34, gLnk("R", "id", "Model8/Tbl34_Attr.htm#Attr397"))
Attr397.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr397.altTxt = "Primary Key"
Attr401 = insDoc(Tbl34, gLnk("R", "code", "Model8/Tbl34_Attr.htm#Attr401"))
Attr401.iconSrc = ICONPATH + "Gif/attr.gif"
Attr401.altTxt = "Column"
Attr398 = insDoc(Tbl34, gLnk("R", "pwd", "Model8/Tbl34_Attr.htm#Attr398"))
Attr398.iconSrc = ICONPATH + "Gif/attr.gif"
Attr398.altTxt = "Column"
Attr399 = insDoc(Tbl34, gLnk("R", "name", "Model8/Tbl34_Attr.htm#Attr399"))
Attr399.iconSrc = ICONPATH + "Gif/attr.gif"
Attr399.altTxt = "Column"
Attr400 = insDoc(Tbl34, gLnk("R", "sex", "Model8/Tbl34_Attr.htm#Attr400"))
Attr400.iconSrc = ICONPATH + "Gif/attr.gif"
Attr400.altTxt = "Column"
Attr407 = insDoc(Tbl34, gLnk("R", "is_delete", "Model8/Tbl34_Attr.htm#Attr407"))
Attr407.iconSrc = ICONPATH + "Gif/attr.gif"
Attr407.altTxt = "Column"
Attr402 = insDoc(Tbl34, gLnk("R", "remark", "Model8/Tbl34_Attr.htm#Attr402"))
Attr402.iconSrc = ICONPATH + "Gif/attr.gif"
Attr402.altTxt = "Column"
Attr403 = insDoc(Tbl34, gLnk("R", "create_by", "Model8/Tbl34_Attr.htm#Attr403"))
Attr403.iconSrc = ICONPATH + "Gif/attr.gif"
Attr403.altTxt = "Column"
Attr404 = insDoc(Tbl34, gLnk("R", "create_date", "Model8/Tbl34_Attr.htm#Attr404"))
Attr404.iconSrc = ICONPATH + "Gif/attr.gif"
Attr404.altTxt = "Column"
Attr405 = insDoc(Tbl34, gLnk("R", "update_by", "Model8/Tbl34_Attr.htm#Attr405"))
Attr405.iconSrc = ICONPATH + "Gif/attr.gif"
Attr405.altTxt = "Column"
Attr406 = insDoc(Tbl34, gLnk("R", "update_date", "Model8/Tbl34_Attr.htm#Attr406"))
Attr406.iconSrc = ICONPATH + "Gif/attr.gif"
Attr406.altTxt = "Column"
}
}
AttrFolder = insFld(Submodel8, gFld("Columns", "javascript:parent.op()"))
AttrFolder.iconSrc = ICONPATH + "Gif/attr.gif"
AttrFolder.iconSrcClosed = ICONPATH + "Gif/attr.gif"
Attr643 = insDoc(AttrFolder, gLnk("R", "access_token.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr643"))
Attr643.iconSrc = ICONPATH + "Gif/attr.gif"
Attr643.altTxt = "Column"
Attr465 = insDoc(AttrFolder, gLnk("R", "address.bus_market", "Model8/Tbl39_Attr.htm#Attr465"))
Attr465.iconSrc = ICONPATH + "Gif/attr.gif"
Attr465.altTxt = "Column"
Attr501 = insDoc(AttrFolder, gLnk("R", "address.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr501"))
Attr501.iconSrc = ICONPATH + "Gif/attr.gif"
Attr501.altTxt = "Column"
Attr630 = insDoc(AttrFolder, gLnk("R", "amount.bus_payment", "Model8/Tbl53_Attr.htm#Attr630"))
Attr630.iconSrc = ICONPATH + "Gif/attr.gif"
Attr630.altTxt = "Column"
Attr555 = insDoc(AttrFolder, gLnk("R", "app_version.bus_user_device", "Model8/Tbl47_Attr.htm#Attr555"))
Attr555.iconSrc = ICONPATH + "Gif/attr.gif"
Attr555.altTxt = "Column"
Attr463 = insDoc(AttrFolder, gLnk("R", "area_id.bus_market", "Model8/Tbl39_Attr.htm#Attr463"))
Attr463.iconSrc = ICONPATH + "Gif/attr.gif"
Attr463.altTxt = "Column"
Attr502 = insDoc(AttrFolder, gLnk("R", "area_id.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr502"))
Attr502.iconSrc = ICONPATH + "Gif/attr.gif"
Attr502.altTxt = "Column"
Attr447 = insDoc(AttrFolder, gLnk("R", "area_type.bus_area", "Model8/Tbl38_Attr.htm#Attr447"))
Attr447.iconSrc = ICONPATH + "Gif/attr.gif"
Attr447.altTxt = "Column"
Attr565 = insDoc(AttrFolder, gLnk("R", "bus_type.bus_image", "Model8/Tbl48_Attr.htm#Attr565"))
Attr565.iconSrc = ICONPATH + "Gif/attr.gif"
Attr565.altTxt = "Column"
Attr603 = insDoc(AttrFolder, gLnk("R", "bus_type.bus_share", "Model8/Tbl51_Attr.htm#Attr603"))
Attr603.iconSrc = ICONPATH + "Gif/attr.gif"
Attr603.altTxt = "Column"
Attr428 = insDoc(AttrFolder, gLnk("R", "code.bus_user", "Model8/Tbl37_Attr.htm#Attr428"))
Attr428.iconSrc = ICONPATH + "Gif/attr.gif"
Attr428.altTxt = "Column"
Attr401 = insDoc(AttrFolder, gLnk("R", "code.sys_user", "Model8/Tbl34_Attr.htm#Attr401"))
Attr401.iconSrc = ICONPATH + "Gif/attr.gif"
Attr401.altTxt = "Column"
Attr596 = insDoc(AttrFolder, gLnk("R", "consignee_name.bus_order", "Model8/Tbl50_Attr.htm#Attr596"))
Attr596.iconSrc = ICONPATH + "Gif/attr.gif"
Attr596.altTxt = "Column"
Attr597 = insDoc(AttrFolder, gLnk("R", "consignee_phone.bus_order", "Model8/Tbl50_Attr.htm#Attr597"))
Attr597.iconSrc = ICONPATH + "Gif/attr.gif"
Attr597.altTxt = "Column"
Attr421 = insDoc(AttrFolder, gLnk("R", "constant_id.sys_constant_detail", "Model8/Tbl36_Attr.htm#Attr421"))
Attr421.iconSrc = ICONPATH + "Gif/attr.gif"
Attr421.altTxt = "Column"
Attr422 = insDoc(AttrFolder, gLnk("R", "constant_key.sys_constant_detail", "Model8/Tbl36_Attr.htm#Attr422"))
Attr422.iconSrc = ICONPATH + "Gif/attr.gif"
Attr422.altTxt = "Column"
Attr423 = insDoc(AttrFolder, gLnk("R", "constant_value.sys_constant_detail", "Model8/Tbl36_Attr.htm#Attr423"))
Attr423.iconSrc = ICONPATH + "Gif/attr.gif"
Attr423.altTxt = "Column"
Attr605 = insDoc(AttrFolder, gLnk("R", "content.bus_share", "Model8/Tbl51_Attr.htm#Attr605"))
Attr605.iconSrc = ICONPATH + "Gif/attr.gif"
Attr605.altTxt = "Column"
Attr640 = insDoc(AttrFolder, gLnk("R", "correlation_code.bus_payment", "Model8/Tbl53_Attr.htm#Attr640"))
Attr640.iconSrc = ICONPATH + "Gif/attr.gif"
Attr640.altTxt = "Column"
Attr624 = insDoc(AttrFolder, gLnk("R", "count.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr624"))
Attr624.iconSrc = ICONPATH + "Gif/attr.gif"
Attr624.altTxt = "Column"
Attr460 = insDoc(AttrFolder, gLnk("R", "craete_date.bus_market", "Model8/Tbl39_Attr.htm#Attr460"))
Attr460.iconSrc = ICONPATH + "Gif/attr.gif"
Attr460.altTxt = "Column"
Attr446 = insDoc(AttrFolder, gLnk("R", "create_by.bus_area", "Model8/Tbl38_Attr.htm#Attr446"))
Attr446.iconSrc = ICONPATH + "Gif/attr.gif"
Attr446.altTxt = "Column"
Attr478 = insDoc(AttrFolder, gLnk("R", "create_by.bus_dish", "Model8/Tbl40_Attr.htm#Attr478"))
Attr478.iconSrc = ICONPATH + "Gif/attr.gif"
Attr478.altTxt = "Column"
Attr495 = insDoc(AttrFolder, gLnk("R", "create_by.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr495"))
Attr495.iconSrc = ICONPATH + "Gif/attr.gif"
Attr495.altTxt = "Column"
Attr570 = insDoc(AttrFolder, gLnk("R", "create_by.bus_image", "Model8/Tbl48_Attr.htm#Attr570"))
Attr570.iconSrc = ICONPATH + "Gif/attr.gif"
Attr570.altTxt = "Column"
Attr459 = insDoc(AttrFolder, gLnk("R", "create_by.bus_market", "Model8/Tbl39_Attr.htm#Attr459"))
Attr459.iconSrc = ICONPATH + "Gif/attr.gif"
Attr459.altTxt = "Column"
Attr587 = insDoc(AttrFolder, gLnk("R", "create_by.bus_order", "Model8/Tbl50_Attr.htm#Attr587"))
Attr587.iconSrc = ICONPATH + "Gif/attr.gif"
Attr587.altTxt = "Column"
Attr620 = insDoc(AttrFolder, gLnk("R", "create_by.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr620"))
Attr620.iconSrc = ICONPATH + "Gif/attr.gif"
Attr620.altTxt = "Column"
Attr635 = insDoc(AttrFolder, gLnk("R", "create_by.bus_payment", "Model8/Tbl53_Attr.htm#Attr635"))
Attr635.iconSrc = ICONPATH + "Gif/attr.gif"
Attr635.altTxt = "Column"
Attr508 = insDoc(AttrFolder, gLnk("R", "create_by.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr508"))
Attr508.iconSrc = ICONPATH + "Gif/attr.gif"
Attr508.altTxt = "Column"
Attr528 = insDoc(AttrFolder, gLnk("R", "create_by.bus_pickup_market", "Model8/Tbl44_Attr.htm#Attr528"))
Attr528.iconSrc = ICONPATH + "Gif/attr.gif"
Attr528.altTxt = "Column"
Attr546 = insDoc(AttrFolder, gLnk("R", "create_by.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr546"))
Attr546.iconSrc = ICONPATH + "Gif/attr.gif"
Attr546.altTxt = "Column"
Attr519 = insDoc(AttrFolder, gLnk("R", "create_by.bus_pickup_user", "Model8/Tbl43_Attr.htm#Attr519"))
Attr519.iconSrc = ICONPATH + "Gif/attr.gif"
Attr519.altTxt = "Column"
Attr610 = insDoc(AttrFolder, gLnk("R", "create_by.bus_share", "Model8/Tbl51_Attr.htm#Attr610"))
Attr610.iconSrc = ICONPATH + "Gif/attr.gif"
Attr610.altTxt = "Column"
Attr580 = insDoc(AttrFolder, gLnk("R", "create_by.bus_times", "Model8/Tbl49_Attr.htm#Attr580"))
Attr580.iconSrc = ICONPATH + "Gif/attr.gif"
Attr580.altTxt = "Column"
Attr430 = insDoc(AttrFolder, gLnk("R", "create_by.bus_user", "Model8/Tbl37_Attr.htm#Attr430"))
Attr430.iconSrc = ICONPATH + "Gif/attr.gif"
Attr430.altTxt = "Column"
Attr537 = insDoc(AttrFolder, gLnk("R", "create_by.bus_user_black_list", "Model8/Tbl45_Attr.htm#Attr537"))
Attr537.iconSrc = ICONPATH + "Gif/attr.gif"
Attr537.altTxt = "Column"
Attr558 = insDoc(AttrFolder, gLnk("R", "create_by.bus_user_device", "Model8/Tbl47_Attr.htm#Attr558"))
Attr558.iconSrc = ICONPATH + "Gif/attr.gif"
Attr558.altTxt = "Column"
Attr649 = insDoc(AttrFolder, gLnk("R", "create_by.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr649"))
Attr649.iconSrc = ICONPATH + "Gif/attr.gif"
Attr649.altTxt = "Column"
Attr410 = insDoc(AttrFolder, gLnk("R", "create_by.sys_constant", "Model8/Tbl35_Attr.htm#Attr410"))
Attr410.iconSrc = ICONPATH + "Gif/attr.gif"
Attr410.altTxt = "Column"
Attr417 = insDoc(AttrFolder, gLnk("R", "create_by.sys_constant_detail", "Model8/Tbl36_Attr.htm#Attr417"))
Attr417.iconSrc = ICONPATH + "Gif/attr.gif"
Attr417.altTxt = "Column"
Attr403 = insDoc(AttrFolder, gLnk("R", "create_by.sys_user", "Model8/Tbl34_Attr.htm#Attr403"))
Attr403.iconSrc = ICONPATH + "Gif/attr.gif"
Attr403.altTxt = "Column"
Attr448 = insDoc(AttrFolder, gLnk("R", "create_date.bus_area", "Model8/Tbl38_Attr.htm#Attr448"))
Attr448.iconSrc = ICONPATH + "Gif/attr.gif"
Attr448.altTxt = "Column"
Attr479 = insDoc(AttrFolder, gLnk("R", "create_date.bus_dish", "Model8/Tbl40_Attr.htm#Attr479"))
Attr479.iconSrc = ICONPATH + "Gif/attr.gif"
Attr479.altTxt = "Column"
Attr496 = insDoc(AttrFolder, gLnk("R", "create_date.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr496"))
Attr496.iconSrc = ICONPATH + "Gif/attr.gif"
Attr496.altTxt = "Column"
Attr571 = insDoc(AttrFolder, gLnk("R", "create_date.bus_image", "Model8/Tbl48_Attr.htm#Attr571"))
Attr571.iconSrc = ICONPATH + "Gif/attr.gif"
Attr571.altTxt = "Column"
Attr588 = insDoc(AttrFolder, gLnk("R", "create_date.bus_order", "Model8/Tbl50_Attr.htm#Attr588"))
Attr588.iconSrc = ICONPATH + "Gif/attr.gif"
Attr588.altTxt = "Column"
Attr621 = insDoc(AttrFolder, gLnk("R", "create_date.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr621"))
Attr621.iconSrc = ICONPATH + "Gif/attr.gif"
Attr621.altTxt = "Column"
Attr636 = insDoc(AttrFolder, gLnk("R", "create_date.bus_payment", "Model8/Tbl53_Attr.htm#Attr636"))
Attr636.iconSrc = ICONPATH + "Gif/attr.gif"
Attr636.altTxt = "Column"
Attr509 = insDoc(AttrFolder, gLnk("R", "create_date.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr509"))
Attr509.iconSrc = ICONPATH + "Gif/attr.gif"
Attr509.altTxt = "Column"
Attr529 = insDoc(AttrFolder, gLnk("R", "create_date.bus_pickup_market", "Model8/Tbl44_Attr.htm#Attr529"))
Attr529.iconSrc = ICONPATH + "Gif/attr.gif"
Attr529.altTxt = "Column"
Attr547 = insDoc(AttrFolder, gLnk("R", "create_date.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr547"))
Attr547.iconSrc = ICONPATH + "Gif/attr.gif"
Attr547.altTxt = "Column"
Attr520 = insDoc(AttrFolder, gLnk("R", "create_date.bus_pickup_user", "Model8/Tbl43_Attr.htm#Attr520"))
Attr520.iconSrc = ICONPATH + "Gif/attr.gif"
Attr520.altTxt = "Column"
Attr611 = insDoc(AttrFolder, gLnk("R", "create_date.bus_share", "Model8/Tbl51_Attr.htm#Attr611"))
Attr611.iconSrc = ICONPATH + "Gif/attr.gif"
Attr611.altTxt = "Column"
Attr581 = insDoc(AttrFolder, gLnk("R", "create_date.bus_times", "Model8/Tbl49_Attr.htm#Attr581"))
Attr581.iconSrc = ICONPATH + "Gif/attr.gif"
Attr581.altTxt = "Column"
Attr431 = insDoc(AttrFolder, gLnk("R", "create_date.bus_user", "Model8/Tbl37_Attr.htm#Attr431"))
Attr431.iconSrc = ICONPATH + "Gif/attr.gif"
Attr431.altTxt = "Column"
Attr538 = insDoc(AttrFolder, gLnk("R", "create_date.bus_user_black_list", "Model8/Tbl45_Attr.htm#Attr538"))
Attr538.iconSrc = ICONPATH + "Gif/attr.gif"
Attr538.altTxt = "Column"
Attr559 = insDoc(AttrFolder, gLnk("R", "create_date.bus_user_device", "Model8/Tbl47_Attr.htm#Attr559"))
Attr559.iconSrc = ICONPATH + "Gif/attr.gif"
Attr559.altTxt = "Column"
Attr650 = insDoc(AttrFolder, gLnk("R", "create_date.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr650"))
Attr650.iconSrc = ICONPATH + "Gif/attr.gif"
Attr650.altTxt = "Column"
Attr411 = insDoc(AttrFolder, gLnk("R", "create_date.sys_constant", "Model8/Tbl35_Attr.htm#Attr411"))
Attr411.iconSrc = ICONPATH + "Gif/attr.gif"
Attr411.altTxt = "Column"
Attr418 = insDoc(AttrFolder, gLnk("R", "create_date.sys_constant_detail", "Model8/Tbl36_Attr.htm#Attr418"))
Attr418.iconSrc = ICONPATH + "Gif/attr.gif"
Attr418.altTxt = "Column"
Attr404 = insDoc(AttrFolder, gLnk("R", "create_date.sys_user", "Model8/Tbl34_Attr.htm#Attr404"))
Attr404.iconSrc = ICONPATH + "Gif/attr.gif"
Attr404.altTxt = "Column"
Attr439 = insDoc(AttrFolder, gLnk("R", "cur_deviceId.bus_user", "Model8/Tbl37_Attr.htm#Attr439"))
Attr439.iconSrc = ICONPATH + "Gif/attr.gif"
Attr439.altTxt = "Column"
Attr484 = insDoc(AttrFolder, gLnk("R", "description_cn.bus_dish", "Model8/Tbl40_Attr.htm#Attr484"))
Attr484.iconSrc = ICONPATH + "Gif/attr.gif"
Attr484.altTxt = "Column"
Attr468 = insDoc(AttrFolder, gLnk("R", "description_cn.bus_market", "Model8/Tbl39_Attr.htm#Attr468"))
Attr468.iconSrc = ICONPATH + "Gif/attr.gif"
Attr468.altTxt = "Column"
Attr475 = insDoc(AttrFolder, gLnk("R", "description_en.bus_dish", "Model8/Tbl40_Attr.htm#Attr475"))
Attr475.iconSrc = ICONPATH + "Gif/attr.gif"
Attr475.altTxt = "Column"
Attr467 = insDoc(AttrFolder, gLnk("R", "description_en.bus_market", "Model8/Tbl39_Attr.htm#Attr467"))
Attr467.iconSrc = ICONPATH + "Gif/attr.gif"
Attr467.altTxt = "Column"
Attr562 = insDoc(AttrFolder, gLnk("R", "device_id.bus_user_device", "Model8/Tbl47_Attr.htm#Attr562"))
Attr562.iconSrc = ICONPATH + "Gif/attr.gif"
Attr562.altTxt = "Column"
Attr563 = insDoc(AttrFolder, gLnk("R", "device_type.bus_user_device", "Model8/Tbl47_Attr.htm#Attr563"))
Attr563.iconSrc = ICONPATH + "Gif/attr.gif"
Attr563.altTxt = "Column"
Attr593 = insDoc(AttrFolder, gLnk("R", "dilivery_user_id.bus_order", "Model8/Tbl50_Attr.htm#Attr593"))
Attr593.iconSrc = ICONPATH + "Gif/attr.gif"
Attr593.altTxt = "Column"
Attr487 = insDoc(AttrFolder, gLnk("R", "discount_price.bus_dish", "Model8/Tbl40_Attr.htm#Attr487"))
Attr487.iconSrc = ICONPATH + "Gif/attr.gif"
Attr487.altTxt = "Column"
Attr489 = insDoc(AttrFolder, gLnk("R", "dish_id.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr489"))
Attr489.iconSrc = ICONPATH + "Gif/attr.gif"
Attr489.altTxt = "Column"
Attr616 = insDoc(AttrFolder, gLnk("R", "dish_id.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr616"))
Attr616.iconSrc = ICONPATH + "Gif/attr.gif"
Attr616.altTxt = "Column"
Attr473 = insDoc(AttrFolder, gLnk("R", "dish_type.bus_dish", "Model8/Tbl40_Attr.htm#Attr473"))
Attr473.iconSrc = ICONPATH + "Gif/attr.gif"
Attr473.altTxt = "Column"
Attr492 = insDoc(AttrFolder, gLnk("R", "dish_type.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr492"))
Attr492.iconSrc = ICONPATH + "Gif/attr.gif"
Attr492.altTxt = "Column"
Attr543 = insDoc(AttrFolder, gLnk("R", "dish_type.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr543"))
Attr543.iconSrc = ICONPATH + "Gif/attr.gif"
Attr543.altTxt = "Column"
Attr491 = insDoc(AttrFolder, gLnk("R", "end_date.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr491"))
Attr491.iconSrc = ICONPATH + "Gif/attr.gif"
Attr491.altTxt = "Column"
Attr577 = insDoc(AttrFolder, gLnk("R", "end_time.bus_times", "Model8/Tbl49_Attr.htm#Attr577"))
Attr577.iconSrc = ICONPATH + "Gif/attr.gif"
Attr577.altTxt = "Column"
Attr644 = insDoc(AttrFolder, gLnk("R", "expires_in.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr644"))
Attr644.iconSrc = ICONPATH + "Gif/attr.gif"
Attr644.altTxt = "Column"
Attr438 = insDoc(AttrFolder, gLnk("R", "generate_time.bus_user", "Model8/Tbl37_Attr.htm#Attr438"))
Attr438.iconSrc = ICONPATH + "Gif/attr.gif"
Attr438.altTxt = "Column"
Attr440 = insDoc(AttrFolder, gLnk("R", "id.bus_area", "Model8/Tbl38_Attr.htm#Attr440"))
Attr440.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr440.altTxt = "Primary Key"
Attr471 = insDoc(AttrFolder, gLnk("R", "id.bus_dish", "Model8/Tbl40_Attr.htm#Attr471"))
Attr471.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr471.altTxt = "Primary Key"
Attr488 = insDoc(AttrFolder, gLnk("R", "id.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr488"))
Attr488.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr488.altTxt = "Primary Key"
Attr564 = insDoc(AttrFolder, gLnk("R", "id.bus_image", "Model8/Tbl48_Attr.htm#Attr564"))
Attr564.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr564.altTxt = "Primary Key"
Attr452 = insDoc(AttrFolder, gLnk("R", "id.bus_market", "Model8/Tbl39_Attr.htm#Attr452"))
Attr452.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr452.altTxt = "Primary Key"
Attr584 = insDoc(AttrFolder, gLnk("R", "id.bus_order", "Model8/Tbl50_Attr.htm#Attr584"))
Attr584.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr584.altTxt = "Primary Key"
Attr614 = insDoc(AttrFolder, gLnk("R", "id.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr614"))
Attr614.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr614.altTxt = "Primary Key"
Attr628 = insDoc(AttrFolder, gLnk("R", "id.bus_payment", "Model8/Tbl53_Attr.htm#Attr628"))
Attr628.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr628.altTxt = "Primary Key"
Attr499 = insDoc(AttrFolder, gLnk("R", "id.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr499"))
Attr499.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr499.altTxt = "Primary Key"
Attr523 = insDoc(AttrFolder, gLnk("R", "id.bus_pickup_market", "Model8/Tbl44_Attr.htm#Attr523"))
Attr523.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr523.altTxt = "Primary Key"
Attr541 = insDoc(AttrFolder, gLnk("R", "id.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr541"))
Attr541.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr541.altTxt = "Primary Key"
Attr514 = insDoc(AttrFolder, gLnk("R", "id.bus_pickup_user", "Model8/Tbl43_Attr.htm#Attr514"))
Attr514.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr514.altTxt = "Primary Key"
Attr602 = insDoc(AttrFolder, gLnk("R", "id.bus_share", "Model8/Tbl51_Attr.htm#Attr602"))
Attr602.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr602.altTxt = "Primary Key"
Attr575 = insDoc(AttrFolder, gLnk("R", "id.bus_times", "Model8/Tbl49_Attr.htm#Attr575"))
Attr575.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr575.altTxt = "Primary Key"
Attr424 = insDoc(AttrFolder, gLnk("R", "id.bus_user", "Model8/Tbl37_Attr.htm#Attr424"))
Attr424.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr424.altTxt = "Primary Key"
Attr532 = insDoc(AttrFolder, gLnk("R", "id.bus_user_black_list", "Model8/Tbl45_Attr.htm#Attr532"))
Attr532.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr532.altTxt = "Primary Key"
Attr551 = insDoc(AttrFolder, gLnk("R", "id.bus_user_device", "Model8/Tbl47_Attr.htm#Attr551"))
Attr551.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr551.altTxt = "Primary Key"
Attr641 = insDoc(AttrFolder, gLnk("R", "id.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr641"))
Attr641.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr641.altTxt = "Primary Key"
Attr408 = insDoc(AttrFolder, gLnk("R", "id.sys_constant", "Model8/Tbl35_Attr.htm#Attr408"))
Attr408.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr408.altTxt = "Primary Key"
Attr415 = insDoc(AttrFolder, gLnk("R", "id.sys_constant_detail", "Model8/Tbl36_Attr.htm#Attr415"))
Attr415.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr415.altTxt = "Primary Key"
Attr397 = insDoc(AttrFolder, gLnk("R", "id.sys_user", "Model8/Tbl34_Attr.htm#Attr397"))
Attr397.iconSrc = ICONPATH + "Gif/pkattr.gif"
Attr397.altTxt = "Primary Key"
Attr566 = insDoc(AttrFolder, gLnk("R", "img_type.bus_image", "Model8/Tbl48_Attr.htm#Attr566"))
Attr566.iconSrc = ICONPATH + "Gif/attr.gif"
Attr566.altTxt = "Column"
Attr451 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_area", "Model8/Tbl38_Attr.htm#Attr451"))
Attr451.iconSrc = ICONPATH + "Gif/attr.gif"
Attr451.altTxt = "Column"
Attr482 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_dish", "Model8/Tbl40_Attr.htm#Attr482"))
Attr482.iconSrc = ICONPATH + "Gif/attr.gif"
Attr482.altTxt = "Column"
Attr493 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr493"))
Attr493.iconSrc = ICONPATH + "Gif/attr.gif"
Attr493.altTxt = "Column"
Attr568 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_image", "Model8/Tbl48_Attr.htm#Attr568"))
Attr568.iconSrc = ICONPATH + "Gif/attr.gif"
Attr568.altTxt = "Column"
Attr464 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_market", "Model8/Tbl39_Attr.htm#Attr464"))
Attr464.iconSrc = ICONPATH + "Gif/attr.gif"
Attr464.altTxt = "Column"
Attr585 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_order", "Model8/Tbl50_Attr.htm#Attr585"))
Attr585.iconSrc = ICONPATH + "Gif/attr.gif"
Attr585.altTxt = "Column"
Attr618 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr618"))
Attr618.iconSrc = ICONPATH + "Gif/attr.gif"
Attr618.altTxt = "Column"
Attr633 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_payment", "Model8/Tbl53_Attr.htm#Attr633"))
Attr633.iconSrc = ICONPATH + "Gif/attr.gif"
Attr633.altTxt = "Column"
Attr506 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr506"))
Attr506.iconSrc = ICONPATH + "Gif/attr.gif"
Attr506.altTxt = "Column"
Attr526 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_pickup_market", "Model8/Tbl44_Attr.htm#Attr526"))
Attr526.iconSrc = ICONPATH + "Gif/attr.gif"
Attr526.altTxt = "Column"
Attr544 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr544"))
Attr544.iconSrc = ICONPATH + "Gif/attr.gif"
Attr544.altTxt = "Column"
Attr517 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_pickup_user", "Model8/Tbl43_Attr.htm#Attr517"))
Attr517.iconSrc = ICONPATH + "Gif/attr.gif"
Attr517.altTxt = "Column"
Attr608 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_share", "Model8/Tbl51_Attr.htm#Attr608"))
Attr608.iconSrc = ICONPATH + "Gif/attr.gif"
Attr608.altTxt = "Column"
Attr578 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_times", "Model8/Tbl49_Attr.htm#Attr578"))
Attr578.iconSrc = ICONPATH + "Gif/attr.gif"
Attr578.altTxt = "Column"
Attr434 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_user", "Model8/Tbl37_Attr.htm#Attr434"))
Attr434.iconSrc = ICONPATH + "Gif/attr.gif"
Attr434.altTxt = "Column"
Attr535 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_user_black_list", "Model8/Tbl45_Attr.htm#Attr535"))
Attr535.iconSrc = ICONPATH + "Gif/attr.gif"
Attr535.altTxt = "Column"
Attr556 = insDoc(AttrFolder, gLnk("R", "is_delete.bus_user_device", "Model8/Tbl47_Attr.htm#Attr556"))
Attr556.iconSrc = ICONPATH + "Gif/attr.gif"
Attr556.altTxt = "Column"
Attr407 = insDoc(AttrFolder, gLnk("R", "is_delete.sys_user", "Model8/Tbl34_Attr.htm#Attr407"))
Attr407.iconSrc = ICONPATH + "Gif/attr.gif"
Attr407.altTxt = "Column"
Attr444 = insDoc(AttrFolder, gLnk("R", "lat.bus_area", "Model8/Tbl38_Attr.htm#Attr444"))
Attr444.iconSrc = ICONPATH + "Gif/attr.gif"
Attr444.altTxt = "Column"
Attr456 = insDoc(AttrFolder, gLnk("R", "lat.bus_market", "Model8/Tbl39_Attr.htm#Attr456"))
Attr456.iconSrc = ICONPATH + "Gif/attr.gif"
Attr456.altTxt = "Column"
Attr504 = insDoc(AttrFolder, gLnk("R", "lat.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr504"))
Attr504.iconSrc = ICONPATH + "Gif/attr.gif"
Attr504.altTxt = "Column"
Attr606 = insDoc(AttrFolder, gLnk("R", "link_url.bus_share", "Model8/Tbl51_Attr.htm#Attr606"))
Attr606.iconSrc = ICONPATH + "Gif/attr.gif"
Attr606.altTxt = "Column"
Attr443 = insDoc(AttrFolder, gLnk("R", "lon.bus_area", "Model8/Tbl38_Attr.htm#Attr443"))
Attr443.iconSrc = ICONPATH + "Gif/attr.gif"
Attr443.altTxt = "Column"
Attr455 = insDoc(AttrFolder, gLnk("R", "lon.bus_market", "Model8/Tbl39_Attr.htm#Attr455"))
Attr455.iconSrc = ICONPATH + "Gif/attr.gif"
Attr455.altTxt = "Column"
Attr503 = insDoc(AttrFolder, gLnk("R", "lon.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr503"))
Attr503.iconSrc = ICONPATH + "Gif/attr.gif"
Attr503.altTxt = "Column"
Attr472 = insDoc(AttrFolder, gLnk("R", "market_id.bus_dish", "Model8/Tbl40_Attr.htm#Attr472"))
Attr472.iconSrc = ICONPATH + "Gif/attr.gif"
Attr472.altTxt = "Column"
Attr600 = insDoc(AttrFolder, gLnk("R", "market_id.bus_order", "Model8/Tbl50_Attr.htm#Attr600"))
Attr600.iconSrc = ICONPATH + "Gif/attr.gif"
Attr600.altTxt = "Column"
Attr525 = insDoc(AttrFolder, gLnk("R", "market_id.bus_pickup_market", "Model8/Tbl44_Attr.htm#Attr525"))
Attr525.iconSrc = ICONPATH + "Gif/attr.gif"
Attr525.altTxt = "Column"
Attr454 = insDoc(AttrFolder, gLnk("R", "market_type.bus_market", "Model8/Tbl39_Attr.htm#Attr454"))
Attr454.iconSrc = ICONPATH + "Gif/attr.gif"
Attr454.altTxt = "Column"
Attr470 = insDoc(AttrFolder, gLnk("R", "markket_code.bus_market", "Model8/Tbl39_Attr.htm#Attr470"))
Attr470.iconSrc = ICONPATH + "Gif/attr.gif"
Attr470.altTxt = "Column"
Attr601 = insDoc(AttrFolder, gLnk("R", "meal_num.bus_order", "Model8/Tbl50_Attr.htm#Attr601"))
Attr601.iconSrc = ICONPATH + "Gif/attr.gif"
Attr601.altTxt = "Column"
Attr442 = insDoc(AttrFolder, gLnk("R", "name.bus_area", "Model8/Tbl38_Attr.htm#Attr442"))
Attr442.iconSrc = ICONPATH + "Gif/attr.gif"
Attr442.altTxt = "Column"
Attr500 = insDoc(AttrFolder, gLnk("R", "name.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr500"))
Attr500.iconSrc = ICONPATH + "Gif/attr.gif"
Attr500.altTxt = "Column"
Attr414 = insDoc(AttrFolder, gLnk("R", "name.sys_constant", "Model8/Tbl35_Attr.htm#Attr414"))
Attr414.iconSrc = ICONPATH + "Gif/attr.gif"
Attr414.altTxt = "Column"
Attr399 = insDoc(AttrFolder, gLnk("R", "name.sys_user", "Model8/Tbl34_Attr.htm#Attr399"))
Attr399.iconSrc = ICONPATH + "Gif/attr.gif"
Attr399.altTxt = "Column"
Attr483 = insDoc(AttrFolder, gLnk("R", "name_cn.bus_dish", "Model8/Tbl40_Attr.htm#Attr483"))
Attr483.iconSrc = ICONPATH + "Gif/attr.gif"
Attr483.altTxt = "Column"
Attr466 = insDoc(AttrFolder, gLnk("R", "name_cn.bus_market", "Model8/Tbl39_Attr.htm#Attr466"))
Attr466.iconSrc = ICONPATH + "Gif/attr.gif"
Attr466.altTxt = "Column"
Attr474 = insDoc(AttrFolder, gLnk("R", "name_en.bus_dish", "Model8/Tbl40_Attr.htm#Attr474"))
Attr474.iconSrc = ICONPATH + "Gif/attr.gif"
Attr474.altTxt = "Column"
Attr453 = insDoc(AttrFolder, gLnk("R", "name_en.bus_market", "Model8/Tbl39_Attr.htm#Attr453"))
Attr453.iconSrc = ICONPATH + "Gif/attr.gif"
Attr453.altTxt = "Column"
Attr426 = insDoc(AttrFolder, gLnk("R", "nickname.bus_user", "Model8/Tbl37_Attr.htm#Attr426"))
Attr426.iconSrc = ICONPATH + "Gif/attr.gif"
Attr426.altTxt = "Column"
Attr646 = insDoc(AttrFolder, gLnk("R", "open_id.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr646"))
Attr646.iconSrc = ICONPATH + "Gif/attr.gif"
Attr646.altTxt = "Column"
Attr615 = insDoc(AttrFolder, gLnk("R", "order_id.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr615"))
Attr615.iconSrc = ICONPATH + "Gif/attr.gif"
Attr615.altTxt = "Column"
Attr631 = insDoc(AttrFolder, gLnk("R", "order_id.bus_payment", "Model8/Tbl53_Attr.htm#Attr631"))
Attr631.iconSrc = ICONPATH + "Gif/attr.gif"
Attr631.altTxt = "Column"
Attr591 = insDoc(AttrFolder, gLnk("R", "order_status.bus_order", "Model8/Tbl50_Attr.htm#Attr591"))
Attr591.iconSrc = ICONPATH + "Gif/attr.gif"
Attr591.altTxt = "Column"
Attr486 = insDoc(AttrFolder, gLnk("R", "original_price.bus_dish", "Model8/Tbl40_Attr.htm#Attr486"))
Attr486.iconSrc = ICONPATH + "Gif/attr.gif"
Attr486.altTxt = "Column"
Attr441 = insDoc(AttrFolder, gLnk("R", "parent_id.bus_area", "Model8/Tbl38_Attr.htm#Attr441"))
Attr441.iconSrc = ICONPATH + "Gif/attr.gif"
Attr441.altTxt = "Column"
Attr629 = insDoc(AttrFolder, gLnk("R", "payment_channel.bus_payment", "Model8/Tbl53_Attr.htm#Attr629"))
Attr629.iconSrc = ICONPATH + "Gif/attr.gif"
Attr629.altTxt = "Column"
Attr592 = insDoc(AttrFolder, gLnk("R", "payment_status.bus_order", "Model8/Tbl50_Attr.htm#Attr592"))
Attr592.iconSrc = ICONPATH + "Gif/attr.gif"
Attr592.altTxt = "Column"
Attr639 = insDoc(AttrFolder, gLnk("R", "payment_type.bus_payment", "Model8/Tbl53_Attr.htm#Attr639"))
Attr639.iconSrc = ICONPATH + "Gif/attr.gif"
Attr639.altTxt = "Column"
Attr435 = insDoc(AttrFolder, gLnk("R", "phone_num.bus_user", "Model8/Tbl37_Attr.htm#Attr435"))
Attr435.iconSrc = ICONPATH + "Gif/attr.gif"
Attr435.altTxt = "Column"
Attr534 = insDoc(AttrFolder, gLnk("R", "phone_num.bus_user_black_list", "Model8/Tbl45_Attr.htm#Attr534"))
Attr534.iconSrc = ICONPATH + "Gif/attr.gif"
Attr534.altTxt = "Column"
Attr553 = insDoc(AttrFolder, gLnk("R", "phone_num.bus_user_device", "Model8/Tbl47_Attr.htm#Attr553"))
Attr553.iconSrc = ICONPATH + "Gif/attr.gif"
Attr553.altTxt = "Column"
Attr607 = insDoc(AttrFolder, gLnk("R", "pic_url.bus_share", "Model8/Tbl51_Attr.htm#Attr607"))
Attr607.iconSrc = ICONPATH + "Gif/attr.gif"
Attr607.altTxt = "Column"
Attr436 = insDoc(AttrFolder, gLnk("R", "pic_url.bus_user", "Model8/Tbl37_Attr.htm#Attr436"))
Attr436.iconSrc = ICONPATH + "Gif/attr.gif"
Attr436.altTxt = "Column"
Attr595 = insDoc(AttrFolder, gLnk("R", "pickup_address_id.bus_order", "Model8/Tbl50_Attr.htm#Attr595"))
Attr595.iconSrc = ICONPATH + "Gif/attr.gif"
Attr595.altTxt = "Column"
Attr524 = insDoc(AttrFolder, gLnk("R", "pickup_address_id.bus_pickup_market", "Model8/Tbl44_Attr.htm#Attr524"))
Attr524.iconSrc = ICONPATH + "Gif/attr.gif"
Attr524.altTxt = "Column"
Attr542 = insDoc(AttrFolder, gLnk("R", "pickup_address_id.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr542"))
Attr542.iconSrc = ICONPATH + "Gif/attr.gif"
Attr542.altTxt = "Column"
Attr515 = insDoc(AttrFolder, gLnk("R", "pickup_address_id.bus_pickup_user", "Model8/Tbl43_Attr.htm#Attr515"))
Attr515.iconSrc = ICONPATH + "Gif/attr.gif"
Attr515.altTxt = "Column"
Attr513 = insDoc(AttrFolder, gLnk("R", "pickup_code.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr513"))
Attr513.iconSrc = ICONPATH + "Gif/attr.gif"
Attr513.altTxt = "Column"
Attr554 = insDoc(AttrFolder, gLnk("R", "pushToken.bus_user_device", "Model8/Tbl47_Attr.htm#Attr554"))
Attr554.iconSrc = ICONPATH + "Gif/attr.gif"
Attr554.altTxt = "Column"
Attr425 = insDoc(AttrFolder, gLnk("R", "pwd.bus_user", "Model8/Tbl37_Attr.htm#Attr425"))
Attr425.iconSrc = ICONPATH + "Gif/attr.gif"
Attr425.altTxt = "Column"
Attr398 = insDoc(AttrFolder, gLnk("R", "pwd.sys_user", "Model8/Tbl34_Attr.htm#Attr398"))
Attr398.iconSrc = ICONPATH + "Gif/attr.gif"
Attr398.altTxt = "Column"
Attr645 = insDoc(AttrFolder, gLnk("R", "refresh_token.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr645"))
Attr645.iconSrc = ICONPATH + "Gif/attr.gif"
Attr645.altTxt = "Column"
Attr445 = insDoc(AttrFolder, gLnk("R", "remark.bus_area", "Model8/Tbl38_Attr.htm#Attr445"))
Attr445.iconSrc = ICONPATH + "Gif/attr.gif"
Attr445.altTxt = "Column"
Attr477 = insDoc(AttrFolder, gLnk("R", "remark.bus_dish", "Model8/Tbl40_Attr.htm#Attr477"))
Attr477.iconSrc = ICONPATH + "Gif/attr.gif"
Attr477.altTxt = "Column"
Attr494 = insDoc(AttrFolder, gLnk("R", "remark.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr494"))
Attr494.iconSrc = ICONPATH + "Gif/attr.gif"
Attr494.altTxt = "Column"
Attr569 = insDoc(AttrFolder, gLnk("R", "remark.bus_image", "Model8/Tbl48_Attr.htm#Attr569"))
Attr569.iconSrc = ICONPATH + "Gif/attr.gif"
Attr569.altTxt = "Column"
Attr458 = insDoc(AttrFolder, gLnk("R", "remark.bus_market", "Model8/Tbl39_Attr.htm#Attr458"))
Attr458.iconSrc = ICONPATH + "Gif/attr.gif"
Attr458.altTxt = "Column"
Attr586 = insDoc(AttrFolder, gLnk("R", "remark.bus_order", "Model8/Tbl50_Attr.htm#Attr586"))
Attr586.iconSrc = ICONPATH + "Gif/attr.gif"
Attr586.altTxt = "Column"
Attr619 = insDoc(AttrFolder, gLnk("R", "remark.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr619"))
Attr619.iconSrc = ICONPATH + "Gif/attr.gif"
Attr619.altTxt = "Column"
Attr634 = insDoc(AttrFolder, gLnk("R", "remark.bus_payment", "Model8/Tbl53_Attr.htm#Attr634"))
Attr634.iconSrc = ICONPATH + "Gif/attr.gif"
Attr634.altTxt = "Column"
Attr507 = insDoc(AttrFolder, gLnk("R", "remark.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr507"))
Attr507.iconSrc = ICONPATH + "Gif/attr.gif"
Attr507.altTxt = "Column"
Attr527 = insDoc(AttrFolder, gLnk("R", "remark.bus_pickup_market", "Model8/Tbl44_Attr.htm#Attr527"))
Attr527.iconSrc = ICONPATH + "Gif/attr.gif"
Attr527.altTxt = "Column"
Attr545 = insDoc(AttrFolder, gLnk("R", "remark.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr545"))
Attr545.iconSrc = ICONPATH + "Gif/attr.gif"
Attr545.altTxt = "Column"
Attr518 = insDoc(AttrFolder, gLnk("R", "remark.bus_pickup_user", "Model8/Tbl43_Attr.htm#Attr518"))
Attr518.iconSrc = ICONPATH + "Gif/attr.gif"
Attr518.altTxt = "Column"
Attr609 = insDoc(AttrFolder, gLnk("R", "remark.bus_share", "Model8/Tbl51_Attr.htm#Attr609"))
Attr609.iconSrc = ICONPATH + "Gif/attr.gif"
Attr609.altTxt = "Column"
Attr579 = insDoc(AttrFolder, gLnk("R", "remark.bus_times", "Model8/Tbl49_Attr.htm#Attr579"))
Attr579.iconSrc = ICONPATH + "Gif/attr.gif"
Attr579.altTxt = "Column"
Attr429 = insDoc(AttrFolder, gLnk("R", "remark.bus_user", "Model8/Tbl37_Attr.htm#Attr429"))
Attr429.iconSrc = ICONPATH + "Gif/attr.gif"
Attr429.altTxt = "Column"
Attr536 = insDoc(AttrFolder, gLnk("R", "remark.bus_user_black_list", "Model8/Tbl45_Attr.htm#Attr536"))
Attr536.iconSrc = ICONPATH + "Gif/attr.gif"
Attr536.altTxt = "Column"
Attr557 = insDoc(AttrFolder, gLnk("R", "remark.bus_user_device", "Model8/Tbl47_Attr.htm#Attr557"))
Attr557.iconSrc = ICONPATH + "Gif/attr.gif"
Attr557.altTxt = "Column"
Attr648 = insDoc(AttrFolder, gLnk("R", "remark.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr648"))
Attr648.iconSrc = ICONPATH + "Gif/attr.gif"
Attr648.altTxt = "Column"
Attr409 = insDoc(AttrFolder, gLnk("R", "remark.sys_constant", "Model8/Tbl35_Attr.htm#Attr409"))
Attr409.iconSrc = ICONPATH + "Gif/attr.gif"
Attr409.altTxt = "Column"
Attr416 = insDoc(AttrFolder, gLnk("R", "remark.sys_constant_detail", "Model8/Tbl36_Attr.htm#Attr416"))
Attr416.iconSrc = ICONPATH + "Gif/attr.gif"
Attr416.altTxt = "Column"
Attr402 = insDoc(AttrFolder, gLnk("R", "remark.sys_user", "Model8/Tbl34_Attr.htm#Attr402"))
Attr402.iconSrc = ICONPATH + "Gif/attr.gif"
Attr402.altTxt = "Column"
Attr476 = insDoc(AttrFolder, gLnk("R", "sales_total.bus_dish", "Model8/Tbl40_Attr.htm#Attr476"))
Attr476.iconSrc = ICONPATH + "Gif/attr.gif"
Attr476.altTxt = "Column"
Attr647 = insDoc(AttrFolder, gLnk("R", "scope.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr647"))
Attr647.iconSrc = ICONPATH + "Gif/attr.gif"
Attr647.altTxt = "Column"
Attr427 = insDoc(AttrFolder, gLnk("R", "sex.bus_user", "Model8/Tbl37_Attr.htm#Attr427"))
Attr427.iconSrc = ICONPATH + "Gif/attr.gif"
Attr427.altTxt = "Column"
Attr400 = insDoc(AttrFolder, gLnk("R", "sex.sys_user", "Model8/Tbl34_Attr.htm#Attr400"))
Attr400.iconSrc = ICONPATH + "Gif/attr.gif"
Attr400.altTxt = "Column"
Attr485 = insDoc(AttrFolder, gLnk("R", "sort.bus_dish", "Model8/Tbl40_Attr.htm#Attr485"))
Attr485.iconSrc = ICONPATH + "Gif/attr.gif"
Attr485.altTxt = "Column"
Attr574 = insDoc(AttrFolder, gLnk("R", "sort.bus_image", "Model8/Tbl48_Attr.htm#Attr574"))
Attr574.iconSrc = ICONPATH + "Gif/attr.gif"
Attr574.altTxt = "Column"
Attr469 = insDoc(AttrFolder, gLnk("R", "sort.bus_market", "Model8/Tbl39_Attr.htm#Attr469"))
Attr469.iconSrc = ICONPATH + "Gif/attr.gif"
Attr469.altTxt = "Column"
Attr512 = insDoc(AttrFolder, gLnk("R", "sort.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr512"))
Attr512.iconSrc = ICONPATH + "Gif/attr.gif"
Attr512.altTxt = "Column"
Attr490 = insDoc(AttrFolder, gLnk("R", "start_date.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr490"))
Attr490.iconSrc = ICONPATH + "Gif/attr.gif"
Attr490.altTxt = "Column"
Attr576 = insDoc(AttrFolder, gLnk("R", "start_time.bus_times", "Model8/Tbl49_Attr.htm#Attr576"))
Attr576.iconSrc = ICONPATH + "Gif/attr.gif"
Attr576.altTxt = "Column"
Attr457 = insDoc(AttrFolder, gLnk("R", "status.bus_market", "Model8/Tbl39_Attr.htm#Attr457"))
Attr457.iconSrc = ICONPATH + "Gif/attr.gif"
Attr457.altTxt = "Column"
Attr505 = insDoc(AttrFolder, gLnk("R", "status.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr505"))
Attr505.iconSrc = ICONPATH + "Gif/attr.gif"
Attr505.altTxt = "Column"
Attr550 = insDoc(AttrFolder, gLnk("R", "times_id.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr550"))
Attr550.iconSrc = ICONPATH + "Gif/attr.gif"
Attr550.altTxt = "Column"
Attr604 = insDoc(AttrFolder, gLnk("R", "title.bus_share", "Model8/Tbl51_Attr.htm#Attr604"))
Attr604.iconSrc = ICONPATH + "Gif/attr.gif"
Attr604.altTxt = "Column"
Attr626 = insDoc(AttrFolder, gLnk("R", "total_discount_price.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr626"))
Attr626.iconSrc = ICONPATH + "Gif/attr.gif"
Attr626.altTxt = "Column"
Attr617 = insDoc(AttrFolder, gLnk("R", "total_original_price.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr617"))
Attr617.iconSrc = ICONPATH + "Gif/attr.gif"
Attr617.altTxt = "Column"
Attr598 = insDoc(AttrFolder, gLnk("R", "total_plan_price.bus_order", "Model8/Tbl50_Attr.htm#Attr598"))
Attr598.iconSrc = ICONPATH + "Gif/attr.gif"
Attr598.altTxt = "Column"
Attr599 = insDoc(AttrFolder, gLnk("R", "total_real_price.bus_order", "Model8/Tbl50_Attr.htm#Attr599"))
Attr599.iconSrc = ICONPATH + "Gif/attr.gif"
Attr599.altTxt = "Column"
Attr627 = insDoc(AttrFolder, gLnk("R", "unit_discount_price.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr627"))
Attr627.iconSrc = ICONPATH + "Gif/attr.gif"
Attr627.altTxt = "Column"
Attr625 = insDoc(AttrFolder, gLnk("R", "unit_original_price.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr625"))
Attr625.iconSrc = ICONPATH + "Gif/attr.gif"
Attr625.altTxt = "Column"
Attr449 = insDoc(AttrFolder, gLnk("R", "update_by.bus_area", "Model8/Tbl38_Attr.htm#Attr449"))
Attr449.iconSrc = ICONPATH + "Gif/attr.gif"
Attr449.altTxt = "Column"
Attr480 = insDoc(AttrFolder, gLnk("R", "update_by.bus_dish", "Model8/Tbl40_Attr.htm#Attr480"))
Attr480.iconSrc = ICONPATH + "Gif/attr.gif"
Attr480.altTxt = "Column"
Attr497 = insDoc(AttrFolder, gLnk("R", "update_by.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr497"))
Attr497.iconSrc = ICONPATH + "Gif/attr.gif"
Attr497.altTxt = "Column"
Attr572 = insDoc(AttrFolder, gLnk("R", "update_by.bus_image", "Model8/Tbl48_Attr.htm#Attr572"))
Attr572.iconSrc = ICONPATH + "Gif/attr.gif"
Attr572.altTxt = "Column"
Attr461 = insDoc(AttrFolder, gLnk("R", "update_by.bus_market", "Model8/Tbl39_Attr.htm#Attr461"))
Attr461.iconSrc = ICONPATH + "Gif/attr.gif"
Attr461.altTxt = "Column"
Attr589 = insDoc(AttrFolder, gLnk("R", "update_by.bus_order", "Model8/Tbl50_Attr.htm#Attr589"))
Attr589.iconSrc = ICONPATH + "Gif/attr.gif"
Attr589.altTxt = "Column"
Attr622 = insDoc(AttrFolder, gLnk("R", "update_by.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr622"))
Attr622.iconSrc = ICONPATH + "Gif/attr.gif"
Attr622.altTxt = "Column"
Attr637 = insDoc(AttrFolder, gLnk("R", "update_by.bus_payment", "Model8/Tbl53_Attr.htm#Attr637"))
Attr637.iconSrc = ICONPATH + "Gif/attr.gif"
Attr637.altTxt = "Column"
Attr510 = insDoc(AttrFolder, gLnk("R", "update_by.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr510"))
Attr510.iconSrc = ICONPATH + "Gif/attr.gif"
Attr510.altTxt = "Column"
Attr530 = insDoc(AttrFolder, gLnk("R", "update_by.bus_pickup_market", "Model8/Tbl44_Attr.htm#Attr530"))
Attr530.iconSrc = ICONPATH + "Gif/attr.gif"
Attr530.altTxt = "Column"
Attr548 = insDoc(AttrFolder, gLnk("R", "update_by.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr548"))
Attr548.iconSrc = ICONPATH + "Gif/attr.gif"
Attr548.altTxt = "Column"
Attr521 = insDoc(AttrFolder, gLnk("R", "update_by.bus_pickup_user", "Model8/Tbl43_Attr.htm#Attr521"))
Attr521.iconSrc = ICONPATH + "Gif/attr.gif"
Attr521.altTxt = "Column"
Attr612 = insDoc(AttrFolder, gLnk("R", "update_by.bus_share", "Model8/Tbl51_Attr.htm#Attr612"))
Attr612.iconSrc = ICONPATH + "Gif/attr.gif"
Attr612.altTxt = "Column"
Attr582 = insDoc(AttrFolder, gLnk("R", "update_by.bus_times", "Model8/Tbl49_Attr.htm#Attr582"))
Attr582.iconSrc = ICONPATH + "Gif/attr.gif"
Attr582.altTxt = "Column"
Attr432 = insDoc(AttrFolder, gLnk("R", "update_by.bus_user", "Model8/Tbl37_Attr.htm#Attr432"))
Attr432.iconSrc = ICONPATH + "Gif/attr.gif"
Attr432.altTxt = "Column"
Attr539 = insDoc(AttrFolder, gLnk("R", "update_by.bus_user_black_list", "Model8/Tbl45_Attr.htm#Attr539"))
Attr539.iconSrc = ICONPATH + "Gif/attr.gif"
Attr539.altTxt = "Column"
Attr560 = insDoc(AttrFolder, gLnk("R", "update_by.bus_user_device", "Model8/Tbl47_Attr.htm#Attr560"))
Attr560.iconSrc = ICONPATH + "Gif/attr.gif"
Attr560.altTxt = "Column"
Attr651 = insDoc(AttrFolder, gLnk("R", "update_by.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr651"))
Attr651.iconSrc = ICONPATH + "Gif/attr.gif"
Attr651.altTxt = "Column"
Attr412 = insDoc(AttrFolder, gLnk("R", "update_by.sys_constant", "Model8/Tbl35_Attr.htm#Attr412"))
Attr412.iconSrc = ICONPATH + "Gif/attr.gif"
Attr412.altTxt = "Column"
Attr419 = insDoc(AttrFolder, gLnk("R", "update_by.sys_constant_detail", "Model8/Tbl36_Attr.htm#Attr419"))
Attr419.iconSrc = ICONPATH + "Gif/attr.gif"
Attr419.altTxt = "Column"
Attr405 = insDoc(AttrFolder, gLnk("R", "update_by.sys_user", "Model8/Tbl34_Attr.htm#Attr405"))
Attr405.iconSrc = ICONPATH + "Gif/attr.gif"
Attr405.altTxt = "Column"
Attr450 = insDoc(AttrFolder, gLnk("R", "update_date.bus_area", "Model8/Tbl38_Attr.htm#Attr450"))
Attr450.iconSrc = ICONPATH + "Gif/attr.gif"
Attr450.altTxt = "Column"
Attr481 = insDoc(AttrFolder, gLnk("R", "update_date.bus_dish", "Model8/Tbl40_Attr.htm#Attr481"))
Attr481.iconSrc = ICONPATH + "Gif/attr.gif"
Attr481.altTxt = "Column"
Attr498 = insDoc(AttrFolder, gLnk("R", "update_date.bus_dish_plan", "Model8/Tbl41_Attr.htm#Attr498"))
Attr498.iconSrc = ICONPATH + "Gif/attr.gif"
Attr498.altTxt = "Column"
Attr573 = insDoc(AttrFolder, gLnk("R", "update_date.bus_image", "Model8/Tbl48_Attr.htm#Attr573"))
Attr573.iconSrc = ICONPATH + "Gif/attr.gif"
Attr573.altTxt = "Column"
Attr462 = insDoc(AttrFolder, gLnk("R", "update_date.bus_market", "Model8/Tbl39_Attr.htm#Attr462"))
Attr462.iconSrc = ICONPATH + "Gif/attr.gif"
Attr462.altTxt = "Column"
Attr590 = insDoc(AttrFolder, gLnk("R", "update_date.bus_order", "Model8/Tbl50_Attr.htm#Attr590"))
Attr590.iconSrc = ICONPATH + "Gif/attr.gif"
Attr590.altTxt = "Column"
Attr623 = insDoc(AttrFolder, gLnk("R", "update_date.bus_order_dish", "Model8/Tbl52_Attr.htm#Attr623"))
Attr623.iconSrc = ICONPATH + "Gif/attr.gif"
Attr623.altTxt = "Column"
Attr638 = insDoc(AttrFolder, gLnk("R", "update_date.bus_payment", "Model8/Tbl53_Attr.htm#Attr638"))
Attr638.iconSrc = ICONPATH + "Gif/attr.gif"
Attr638.altTxt = "Column"
Attr511 = insDoc(AttrFolder, gLnk("R", "update_date.bus_pickup_address", "Model8/Tbl42_Attr.htm#Attr511"))
Attr511.iconSrc = ICONPATH + "Gif/attr.gif"
Attr511.altTxt = "Column"
Attr531 = insDoc(AttrFolder, gLnk("R", "update_date.bus_pickup_market", "Model8/Tbl44_Attr.htm#Attr531"))
Attr531.iconSrc = ICONPATH + "Gif/attr.gif"
Attr531.altTxt = "Column"
Attr549 = insDoc(AttrFolder, gLnk("R", "update_date.bus_pickup_times", "Model8/Tbl46_Attr.htm#Attr549"))
Attr549.iconSrc = ICONPATH + "Gif/attr.gif"
Attr549.altTxt = "Column"
Attr522 = insDoc(AttrFolder, gLnk("R", "update_date.bus_pickup_user", "Model8/Tbl43_Attr.htm#Attr522"))
Attr522.iconSrc = ICONPATH + "Gif/attr.gif"
Attr522.altTxt = "Column"
Attr613 = insDoc(AttrFolder, gLnk("R", "update_date.bus_share", "Model8/Tbl51_Attr.htm#Attr613"))
Attr613.iconSrc = ICONPATH + "Gif/attr.gif"
Attr613.altTxt = "Column"
Attr583 = insDoc(AttrFolder, gLnk("R", "update_date.bus_times", "Model8/Tbl49_Attr.htm#Attr583"))
Attr583.iconSrc = ICONPATH + "Gif/attr.gif"
Attr583.altTxt = "Column"
Attr433 = insDoc(AttrFolder, gLnk("R", "update_date.bus_user", "Model8/Tbl37_Attr.htm#Attr433"))
Attr433.iconSrc = ICONPATH + "Gif/attr.gif"
Attr433.altTxt = "Column"
Attr540 = insDoc(AttrFolder, gLnk("R", "update_date.bus_user_black_list", "Model8/Tbl45_Attr.htm#Attr540"))
Attr540.iconSrc = ICONPATH + "Gif/attr.gif"
Attr540.altTxt = "Column"
Attr561 = insDoc(AttrFolder, gLnk("R", "update_date.bus_user_device", "Model8/Tbl47_Attr.htm#Attr561"))
Attr561.iconSrc = ICONPATH + "Gif/attr.gif"
Attr561.altTxt = "Column"
Attr652 = insDoc(AttrFolder, gLnk("R", "update_date.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr652"))
Attr652.iconSrc = ICONPATH + "Gif/attr.gif"
Attr652.altTxt = "Column"
Attr413 = insDoc(AttrFolder, gLnk("R", "update_date.sys_constant", "Model8/Tbl35_Attr.htm#Attr413"))
Attr413.iconSrc = ICONPATH + "Gif/attr.gif"
Attr413.altTxt = "Column"
Attr420 = insDoc(AttrFolder, gLnk("R", "update_date.sys_constant_detail", "Model8/Tbl36_Attr.htm#Attr420"))
Attr420.iconSrc = ICONPATH + "Gif/attr.gif"
Attr420.altTxt = "Column"
Attr406 = insDoc(AttrFolder, gLnk("R", "update_date.sys_user", "Model8/Tbl34_Attr.htm#Attr406"))
Attr406.iconSrc = ICONPATH + "Gif/attr.gif"
Attr406.altTxt = "Column"
Attr567 = insDoc(AttrFolder, gLnk("R", "url.bus_image", "Model8/Tbl48_Attr.htm#Attr567"))
Attr567.iconSrc = ICONPATH + "Gif/attr.gif"
Attr567.altTxt = "Column"
Attr594 = insDoc(AttrFolder, gLnk("R", "user_id.bus_order", "Model8/Tbl50_Attr.htm#Attr594"))
Attr594.iconSrc = ICONPATH + "Gif/attr.gif"
Attr594.altTxt = "Column"
Attr632 = insDoc(AttrFolder, gLnk("R", "user_id.bus_payment", "Model8/Tbl53_Attr.htm#Attr632"))
Attr632.iconSrc = ICONPATH + "Gif/attr.gif"
Attr632.altTxt = "Column"
Attr516 = insDoc(AttrFolder, gLnk("R", "user_id.bus_pickup_user", "Model8/Tbl43_Attr.htm#Attr516"))
Attr516.iconSrc = ICONPATH + "Gif/attr.gif"
Attr516.altTxt = "Column"
Attr552 = insDoc(AttrFolder, gLnk("R", "user_id.bus_user_device", "Model8/Tbl47_Attr.htm#Attr552"))
Attr552.iconSrc = ICONPATH + "Gif/attr.gif"
Attr552.altTxt = "Column"
Attr642 = insDoc(AttrFolder, gLnk("R", "user_id.bus_wx_user", "Model8/Tbl54_Attr.htm#Attr642"))
Attr642.iconSrc = ICONPATH + "Gif/attr.gif"
Attr642.altTxt = "Column"
Attr437 = insDoc(AttrFolder, gLnk("R", "user_type.bus_user", "Model8/Tbl37_Attr.htm#Attr437"))
Attr437.iconSrc = ICONPATH + "Gif/attr.gif"
Attr437.altTxt = "Column"
Attr533 = insDoc(AttrFolder, gLnk("R", "user_type.bus_user_black_list", "Model8/Tbl45_Attr.htm#Attr533"))
Attr533.iconSrc = ICONPATH + "Gif/attr.gif"
Attr533.altTxt = "Column"
{
IndexFolder = insFld(Submodel8, gFld("Indexes", "javascript:parent.op()"))
IndexFolder.iconSrc = ICONPATH + "Gif/index.gif"
IndexFolder.iconSrcClosed = ICONPATH + "Gif/index.gif"
Index38 = insDoc(IndexFolder, gLnk("R", "bus_area.PK5", "Model8/Submodel8_idx.htm#Index38"))
Index38.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index38.altTxt = "Index"
Index40 = insDoc(IndexFolder, gLnk("R", "bus_dish.PK7", "Model8/Submodel8_idx.htm#Index40"))
Index40.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index40.altTxt = "Index"
Index41 = insDoc(IndexFolder, gLnk("R", "bus_dish_plan.PK10", "Model8/Submodel8_idx.htm#Index41"))
Index41.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index41.altTxt = "Index"
Index48 = insDoc(IndexFolder, gLnk("R", "bus_image.PK20", "Model8/Submodel8_idx.htm#Index48"))
Index48.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index48.altTxt = "Index"
Index39 = insDoc(IndexFolder, gLnk("R", "bus_market.PK6", "Model8/Submodel8_idx.htm#Index39"))
Index39.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index39.altTxt = "Index"
Index50 = insDoc(IndexFolder, gLnk("R", "bus_order.PK22", "Model8/Submodel8_idx.htm#Index50"))
Index50.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index50.altTxt = "Index"
Index52 = insDoc(IndexFolder, gLnk("R", "bus_order_dish.PK24", "Model8/Submodel8_idx.htm#Index52"))
Index52.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index52.altTxt = "Index"
Index53 = insDoc(IndexFolder, gLnk("R", "bus_payment.PK25", "Model8/Submodel8_idx.htm#Index53"))
Index53.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index53.altTxt = "Index"
Index42 = insDoc(IndexFolder, gLnk("R", "bus_pickup_address.PK11", "Model8/Submodel8_idx.htm#Index42"))
Index42.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index42.altTxt = "Index"
Index44 = insDoc(IndexFolder, gLnk("R", "bus_pickup_market.PK13", "Model8/Submodel8_idx.htm#Index44"))
Index44.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index44.altTxt = "Index"
Index46 = insDoc(IndexFolder, gLnk("R", "bus_pickup_times.PK18", "Model8/Submodel8_idx.htm#Index46"))
Index46.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index46.altTxt = "Index"
Index43 = insDoc(IndexFolder, gLnk("R", "bus_pickup_user.PK12", "Model8/Submodel8_idx.htm#Index43"))
Index43.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index43.altTxt = "Index"
Index51 = insDoc(IndexFolder, gLnk("R", "bus_share.PK23", "Model8/Submodel8_idx.htm#Index51"))
Index51.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index51.altTxt = "Index"
Index49 = insDoc(IndexFolder, gLnk("R", "bus_times.PK21", "Model8/Submodel8_idx.htm#Index49"))
Index49.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index49.altTxt = "Index"
Index37 = insDoc(IndexFolder, gLnk("R", "bus_user.PK1_2", "Model8/Submodel8_idx.htm#Index37"))
Index37.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index37.altTxt = "Index"
Index45 = insDoc(IndexFolder, gLnk("R", "bus_user_black_list.PK17", "Model8/Submodel8_idx.htm#Index45"))
Index45.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index45.altTxt = "Index"
Index47 = insDoc(IndexFolder, gLnk("R", "bus_user_device.PK19", "Model8/Submodel8_idx.htm#Index47"))
Index47.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index47.altTxt = "Index"
Index54 = insDoc(IndexFolder, gLnk("R", "bus_wx_user.PK26", "Model8/Submodel8_idx.htm#Index54"))
Index54.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index54.altTxt = "Index"
Index35 = insDoc(IndexFolder, gLnk("R", "sys_constant.PK1_1", "Model8/Submodel8_idx.htm#Index35"))
Index35.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index35.altTxt = "Index"
Index36 = insDoc(IndexFolder, gLnk("R", "sys_constant_detail.PK1_1_1", "Model8/Submodel8_idx.htm#Index36"))
Index36.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index36.altTxt = "Index"
Index34 = insDoc(IndexFolder, gLnk("R", "sys_user.PK1", "Model8/Submodel8_idx.htm#Index34"))
Index34.iconSrc = ICONPATH + "Gif/pkindex.gif"
Index34.altTxt = "Index"
}
}
}
