//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Web.bus_wx_user {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtuser_id;
		protected global::System.Web.UI.WebControls.TextBox txtaccess_token;
		protected global::System.Web.UI.WebControls.TextBox txtexpires_in;
		protected global::System.Web.UI.WebControls.TextBox txtrefresh_token;
		protected global::System.Web.UI.WebControls.TextBox txtopen_id;
		protected global::System.Web.UI.WebControls.TextBox txtscope;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
		protected global::System.Web.UI.WebControls.TextBox txtcreate_by;
		protected global::System.Web.UI.WebControls.TextBox txtcreate_date;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_by;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_date;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
