//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Web.bus_wx_user {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lbluser_id;
	protected global::System.Web.UI.WebControls.Label lblaccess_token;
	protected global::System.Web.UI.WebControls.Label lblexpires_in;
	protected global::System.Web.UI.WebControls.Label lblrefresh_token;
	protected global::System.Web.UI.WebControls.Label lblopen_id;
	protected global::System.Web.UI.WebControls.Label lblscope;
	protected global::System.Web.UI.WebControls.Label lblremark;
	protected global::System.Web.UI.WebControls.Label lblcreate_by;
	protected global::System.Web.UI.WebControls.Label lblcreate_date;
	protected global::System.Web.UI.WebControls.Label lblupdate_by;
	protected global::System.Web.UI.WebControls.Label lblupdate_date;


       
    }
}
