//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Web.bus_market {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtmarkket_code;
		protected global::System.Web.UI.WebControls.TextBox txtname_en;
		protected global::System.Web.UI.WebControls.TextBox txtname_cn;
		protected global::System.Web.UI.WebControls.TextBox txtmarket_type;
		protected global::System.Web.UI.WebControls.TextBox txtarea_id;
		protected global::System.Web.UI.WebControls.TextBox txtlon;
		protected global::System.Web.UI.WebControls.TextBox txtlat;
		protected global::System.Web.UI.WebControls.TextBox txtaddress;
		protected global::System.Web.UI.WebControls.TextBox txtdescription_en;
		protected global::System.Web.UI.WebControls.TextBox txtdescription_cn;
		protected global::System.Web.UI.WebControls.TextBox txtstatus;
		protected global::System.Web.UI.WebControls.TextBox txtsort;
		protected global::System.Web.UI.WebControls.TextBox txtis_delete;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
		protected global::System.Web.UI.WebControls.TextBox txtcreate_by;
		protected global::System.Web.UI.WebControls.TextBox txtcraete_date;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_by;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_date;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
