//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Web.bus_verify_code {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblphone_num;
	protected global::System.Web.UI.WebControls.Label lblcode;
	protected global::System.Web.UI.WebControls.Label lblverify_type;
	protected global::System.Web.UI.WebControls.Label lblis_delete;
	protected global::System.Web.UI.WebControls.Label lblremark;
	protected global::System.Web.UI.WebControls.Label lblcreate_by;
	protected global::System.Web.UI.WebControls.Label lblcreate_date;
	protected global::System.Web.UI.WebControls.Label lblupdate_by;
	protected global::System.Web.UI.WebControls.Label lblupdate_date;


       
    }
}
