//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Web.bus_order {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtorder_status;
		protected global::System.Web.UI.WebControls.TextBox txtpayment_status;
		protected global::System.Web.UI.WebControls.TextBox txtmarket_id;
		protected global::System.Web.UI.WebControls.TextBox txtuser_id;
		protected global::System.Web.UI.WebControls.TextBox txtdilivery_user_id;
		protected global::System.Web.UI.WebControls.TextBox txtpickup_address_id;
		protected global::System.Web.UI.WebControls.TextBox txtconsignee_name;
		protected global::System.Web.UI.WebControls.TextBox txtconsignee_phone;
		protected global::System.Web.UI.WebControls.TextBox txttotal_plan_price;
		protected global::System.Web.UI.WebControls.TextBox txttotal_real_price;
		protected global::System.Web.UI.WebControls.TextBox txtmeal_num;
		protected global::System.Web.UI.WebControls.TextBox txtis_delete;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
		protected global::System.Web.UI.WebControls.TextBox txtcreate_by;
		protected global::System.Web.UI.WebControls.TextBox txtcreate_date;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_by;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_date;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
