//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Web.bus_payment {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtpay_channel;
		protected global::System.Web.UI.WebControls.TextBox txtpay_type;
		protected global::System.Web.UI.WebControls.TextBox txtamount;
		protected global::System.Web.UI.WebControls.TextBox txtorder_id;
		protected global::System.Web.UI.WebControls.TextBox txtuser_id;
		protected global::System.Web.UI.WebControls.TextBox txtcorrelation_code;
		protected global::System.Web.UI.WebControls.TextBox txtis_delete;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
		protected global::System.Web.UI.WebControls.TextBox txtcreate_by;
		protected global::System.Web.UI.WebControls.TextBox txtcreate_date;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_by;
		protected global::System.Web.UI.WebControls.TextBox txtupdate_date;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
